///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace BackOffice
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the _BackOfficeRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("7ff8f337-aa43-48f9-b5ed-2640ff5cc94e")]
    public partial class _BackOfficeRepository : RepoGenBaseFolder
    {
        static _BackOfficeRepository instance = new _BackOfficeRepository();
        _BackOfficeRepositoryFolders.BackOfficeAppFolder _backoffice;
        _BackOfficeRepositoryFolders.CP3AppFolder _cp3;

        /// <summary>
        /// Gets the singleton class instance representing the _BackOfficeRepository element repository.
        /// </summary>
        [RepositoryFolder("7ff8f337-aa43-48f9-b5ed-2640ff5cc94e")]
        public static _BackOfficeRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public _BackOfficeRepository() 
            : base("_BackOfficeRepository", "/", null, 0, false, "7ff8f337-aa43-48f9-b5ed-2640ff5cc94e", ".\\RepositoryImages\\_BackOfficeRepository7ff8f337.rximgres")
        {
            _backoffice = new _BackOfficeRepositoryFolders.BackOfficeAppFolder(this);
            _cp3 = new _BackOfficeRepositoryFolders.CP3AppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("7ff8f337-aa43-48f9-b5ed-2640ff5cc94e")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The BackOffice folder.
        /// </summary>
        [RepositoryFolder("caa3c3ad-7fc6-453d-b4c8-aab07fd99cb5")]
        public virtual _BackOfficeRepositoryFolders.BackOfficeAppFolder BackOffice
        {
            get { return _backoffice; }
        }

        /// <summary>
        /// The CP3 folder.
        /// </summary>
        [RepositoryFolder("940286d5-7043-446c-ac46-a9ae1f08b968")]
        public virtual _BackOfficeRepositoryFolders.CP3AppFolder CP3
        {
            get { return _cp3; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class _BackOfficeRepositoryFolders
    {
        /// <summary>
        /// The BackOfficeAppFolder folder.
        /// </summary>
        [RepositoryFolder("caa3c3ad-7fc6-453d-b4c8-aab07fd99cb5")]
        public partial class BackOfficeAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _usernameInfo;
            RepoItemInfo _passwordInfo;
            RepoItemInfo _login_btnInfo;
            RepoItemInfo _adminmenulistitemInfo;
            RepoItemInfo _usersInfo;
            RepoItemInfo _surnamedisplayvalueInfo;
            RepoItemInfo _addinternalbuttonInfo;
            RepoItemInfo _internaluser_usernameInfo;
            RepoItemInfo _loading_modalInfo;
            RepoItemInfo _usermenuitemInfo;
            RepoItemInfo _usermenuitem_logoutbuttonInfo;
            RepoItemInfo _logout_btnInfo;
            RepoItemInfo _requestsmenuitemInfo;
            RepoItemInfo _newrequestInfo;
            RepoItemInfo _homemenuitemInfo;
            RepoItemInfo _clientsearch_nameInfo;
            RepoItemInfo _clientname_zztestenergycompanyInfo;
            RepoItemInfo _newmultiactivityrequestheadertextInfo;
            RepoItemInfo _newmultiactivityrequest_classpolicy_selectInfo;
            RepoItemInfo _newmultiactivityrequest_policy_pro000452025_utilityInfo;
            RepoItemInfo _newmultiactivityrequest_policy_pro000462021_propertyInfo;
            RepoItemInfo _newmultiactivityrequest_activitytype_selectInfo;
            RepoItemInfo _newmultiactivityrequest_activitytype_select_riskassessmentInfo;
            RepoItemInfo _newmultiactivityrequest_focus_selectInfo;
            RepoItemInfo _newmultiactivityrequest_engineerInfo;
            RepoItemInfo _submitrequest_btnInfo;
            RepoItemInfo _successmessagesInfo;
            RepoItemInfo _activitysearch_search_btnInfo;
            RepoItemInfo _activitysearch_results_textInfo;
            RepoItemInfo _resultsgrid_select_btn_row1Info;
            RepoItemInfo _assigntoadministrator_btnInfo;
            RepoItemInfo _assign_dialog_select_btnInfo;
            RepoItemInfo _assignprompt_yes_btnInfo;
            RepoItemInfo _assignsuccessful_ok_btnInfo;
            RepoItemInfo _activitydetails_assignedtoadminnameInfo;
            RepoItemInfo _activites_activitydetailstabInfo;
            RepoItemInfo _activities_resultssummarytabInfo;
            RepoItemInfo _resultssummarytab_approve_btnInfo;
            RepoItemInfo _approveactivity_modal_continue_btnInfo;
            RepoItemInfo _activityhasbeenapproved_ok_btnInfo;
            RepoItemInfo _activitystatusfieldstatusidInfo;
            RepoItemInfo _activitydetails_activitystatusfield_readyfordistributionInfo;
            RepoItemInfo _activitydetails_activitystatusfield_distributedInfo;
            RepoItemInfo _resultssummarytab_distribute_btnInfo;
            RepoItemInfo _selectreportrecipients_ok_btn_64Info;
            RepoItemInfo _selectreportrecipients_ok_btn_66Info;
            RepoItemInfo _confirmemailtobesent_send_btnInfo;
            RepoItemInfo _emailconfirmation_ok_btn_72Info;
            RepoItemInfo _emailconfirmation_ok_btn_73Info;
            RepoItemInfo _emailconfirmation_ok_btn_74Info;
            RepoItemInfo _activitysearchresults_activityid_row1Info;
            RepoItemInfo _activityuniqueiddisplayvalueInfo;
            RepoItemInfo _activitydetailstab_client_textInfo;
            RepoItemInfo _usersearch_results_edit_btn_row1Info;
            RepoItemInfo _internaluser_isactiveInfo;
            RepoItemInfo _internaluser_save_btnInfo;
            RepoItemInfo _externaluser_save_btnInfo;
            RepoItemInfo _consultantportaluserInfo;
            RepoItemInfo _loginwasunsuccessfulpleasecorrecttInfo;
            RepoItemInfo _customerportalclass_combined_checkboxInfo;

            /// <summary>
            /// Creates a new BackOffice  folder.
            /// </summary>
            public BackOfficeAppFolder(RepoGenBaseFolder parentFolder) :
                    base("BackOffice", "/dom[@domain>'backoffice']", parentFolder, 5000, null, false, "caa3c3ad-7fc6-453d-b4c8-aab07fd99cb5", "")
            {
                _usernameInfo = new RepoItemInfo(this, "UserName", ".//input[#'UserName']", ".//input[#'UserName']", 30000, null, "d1498fdd-de77-47d0-9590-24ab7d1761d2");
                _passwordInfo = new RepoItemInfo(this, "Password", ".//input[#'Password']", ".//input[#'Password']", 30000, null, "64cf3923-cb84-44ca-bc4d-7b670d0a9f94");
                _login_btnInfo = new RepoItemInfo(this, "LogIn_Btn", ".//button[#'submitButton']", ".//button[#'submitButton']", 30000, null, "3f88cce4-08cf-41e9-8e6f-93920710942c");
                _adminmenulistitemInfo = new RepoItemInfo(this, "AdminMenuListItem", ".//li[#'AdminMenuListItem']", ".//li[#'AdminMenuListItem']", 30000, null, "64a436d5-db7d-4805-b18e-eab529cbeed6");
                _usersInfo = new RepoItemInfo(this, "Users", ".//ul[#'AdminSubMenu']/?/?/a[@innertext='Users']", ".//ul[#'AdminSubMenu']/?/?/a[@innertext='Users']", 30000, null, "d2567940-c044-4d5a-b8b4-d7a58def3de7");
                _surnamedisplayvalueInfo = new RepoItemInfo(this, "SurnameDisplayValue", ".//input[#'Surname_DisplayValue']", ".//input[#'Surname_DisplayValue']", 30000, null, "17fde772-4b8d-4fde-959b-053ce6e6a6e3");
                _addinternalbuttonInfo = new RepoItemInfo(this, "AddInternalButton", ".//button[#'AddInternalButton']", ".//button[#'AddInternalButton']", 30000, null, "1e720a3c-cfdb-4341-bec3-dfc476edac00");
                _internaluser_usernameInfo = new RepoItemInfo(this, "InternalUser_Username", ".//input[#'Username']", ".//input[#'Username']", 30000, null, "b0c3725a-df5e-4197-98b4-3826f861361f");
                _loading_modalInfo = new RepoItemInfo(this, "Loading_Modal", ".//div[#'DivPageBusyText']", ".//div[#'DivPageBusyText']", 30000, null, "cac4c031-4424-462c-a4bb-5b56bc87801a");
                _usermenuitemInfo = new RepoItemInfo(this, "UserMenuItem", ".//a[#'UserMenuItem']", ".//a[#'UserMenuItem']", 30000, null, "1cf6717f-18cc-4c90-8ee5-c55bd8c53aff");
                _usermenuitem_logoutbuttonInfo = new RepoItemInfo(this, "UserMenuItem_LogoutButton", ".//a[#'logoutButton']", ".//a[#'logoutButton']", 30000, null, "dbe6ead6-f226-45b0-949d-11fd02bcbfd6");
                _logout_btnInfo = new RepoItemInfo(this, "Logout_Btn", ".//button[@innertext='Logout']", ".//button[@innertext='Logout']", 30000, null, "7684af78-3847-4a5a-90fa-6692227abda4");
                _requestsmenuitemInfo = new RepoItemInfo(this, "RequestsMenuItem", ".//a[#'RequestsMenuItem']", ".//a[#'RequestsMenuItem']", 30000, null, "62f9f025-d766-4860-b39f-54a8b7158b31");
                _newrequestInfo = new RepoItemInfo(this, "NewRequest", ".//ul[#'RequestSubMenu']/?/?/a[@innertext='New Request']", ".//ul[#'RequestSubMenu']/?/?/a[@innertext='New Request']", 30000, null, "addbd8b8-86ee-4ae1-b158-9ab2b841b65e");
                _homemenuitemInfo = new RepoItemInfo(this, "HomeMenuItem", ".//a[#'HomeMenuItem']", ".//a[#'HomeMenuItem']", 30000, null, "807d55bb-c583-48f1-ac75-3d442fc93929");
                _clientsearch_nameInfo = new RepoItemInfo(this, "ClientSearch_Name", ".//input[#'Name_DisplayValue']", ".//input[#'Name_DisplayValue']", 30000, null, "7b7cc824-db48-492f-8535-436f77c1590a");
                _clientname_zztestenergycompanyInfo = new RepoItemInfo(this, "ClientName_ZZTestEnergyCompany", ".//div[@innertext='ZZTest Energy Company']", ".//div[@innertext='ZZTest Energy Company']", 30000, null, "c9ac06db-3d12-4757-bd9c-bc64240a96a9");
                _newmultiactivityrequestheadertextInfo = new RepoItemInfo(this, "NewMultiActivityRequestHeaderText", ".//fieldset[#'AddRequestFieldset']/legend[@innertext>'New Multi Activity Reques']", ".//fieldset[#'AddRequestFieldset']/legend[@innertext>'New Multi Activity Reques']", 30000, null, "0e0d44c1-bf64-4f3a-920b-6cc40d9f40c2");
                _newmultiactivityrequest_classpolicy_selectInfo = new RepoItemInfo(this, "NewMultiActivityRequest_ClassPolicy_Select", ".//select[#'SelectedClassPolicy']", ".//select[#'SelectedClassPolicy']", 30000, null, "016cdfc3-e21f-4ab8-94c9-bac9d8b67873");
                _newmultiactivityrequest_policy_pro000452025_utilityInfo = new RepoItemInfo(this, "NewMultiActivityRequest_Policy_PRO000452025_Utility", ".//select[#'SelectedClassPolicy']/option[@innertext='PRO000452025']", ".//select[#'SelectedClassPolicy']/option[@innertext='PRO000452025']", 30000, null, "8f36980c-7956-4ee3-a982-9234fca0f44d");
                _newmultiactivityrequest_policy_pro000462021_propertyInfo = new RepoItemInfo(this, "NewMultiActivityRequest_Policy_PRO000462021_Property", ".//select[#'SelectedClassPolicy']/option[@innertext~'PRO000462021']", ".//select[#'SelectedClassPolicy']/option[@innertext='PRO000462021']", 30000, null, "67d00a5f-3d07-4e3f-8ba3-89918909e957");
                _newmultiactivityrequest_activitytype_selectInfo = new RepoItemInfo(this, "NewMultiActivityRequest_ActivityType_Select", ".//table[#'clientLocationTable']//select[@name='ClientDivisionLocationData.MultiActivityLocationList[0].LocationActivities[0].ActivityTypeId']", ".//table[#'clientLocationTable']//select[@name='ClientDivisionLocationData.MultiActivityLocationList[0].LocationActivities[0].ActivityTypeId']", 30000, null, "a2747e2b-fadc-4d86-8c39-a87d5350e11c");
                _newmultiactivityrequest_activitytype_select_riskassessmentInfo = new RepoItemInfo(this, "NewMultiActivityRequest_ActivityType_Select_RiskAssessment", ".//table[#'clientLocationTable']//option[@innertext='Risk Assessment (S)']", ".//table[#'clientLocationTable']//option[@value>'f0568308-ced6-4e52-a5e3-b']", 30000, null, "d6741907-8f3f-4dc3-8133-102bd999b60d");
                _newmultiactivityrequest_focus_selectInfo = new RepoItemInfo(this, "NewMultiActivityRequest_Focus_Select", ".//table[#'clientLocationTable']//select[@name='ClientDivisionLocationData.MultiActivityLocationList[0].LocationActivities[0].ActivityFocusId']", ".//table[#'clientLocationTable']//select[@name='ClientDivisionLocationData.MultiActivityLocationList[0].LocationActivities[0].ActivityFocusId']", 30000, null, "656798f4-48c1-429c-8a37-c415e2bd51df");
                _newmultiactivityrequest_engineerInfo = new RepoItemInfo(this, "NewMultiActivityRequest_Engineer", ".//table[#'clientLocationTable']//select[@name='ClientDivisionLocationData.MultiActivityLocationList[0].LocationActivities[0].AssignedToID']", ".//table[#'clientLocationTable']//select[@name='ClientDivisionLocationData.MultiActivityLocationList[0].LocationActivities[0].AssignedToID']", 30000, null, "41ee6a97-5758-4c8e-99dd-d82abf42a55b");
                _submitrequest_btnInfo = new RepoItemInfo(this, "SubmitRequest_Btn", ".//input[#'submitRequest']", ".//input[#'submitRequest']", 30000, null, "5f57dadf-4ba2-4fe5-9efa-410d4034f258");
                _successmessagesInfo = new RepoItemInfo(this, "SuccessMessages", ".//div[#'divSuccessMessages']", ".//div[#'divSuccessMessages']", 30000, null, "9dabedb3-db57-4a83-98dd-d2491b9ff4fd");
                _activitysearch_search_btnInfo = new RepoItemInfo(this, "ActivitySearch_Search_Btn", ".//form[#'form0']//input[@type='submit']", ".//form[#'form0']//input[@type='submit']", 30000, null, "731702ee-6d96-4549-a1ce-c2b2a42fd7d0");
                _activitysearch_results_textInfo = new RepoItemInfo(this, "ActivitySearch_Results_Text", ".//div[#'main']/?/?/legend[@innertext='Results']", ".//div[#'main']/?/?/legend[@innertext='Results']", 30000, null, "be6740ea-f568-452d-96e7-a0fe20ba7a74");
                _resultsgrid_select_btn_row1Info = new RepoItemInfo(this, "ResultsGrid_Select_Btn_Row1", ".//table[#'MaintainActivitiesGrid']//button[@innertext~'Select']", ".//table[#'MaintainActivitiesGrid']//button[@innertext='            Select']", 30000, null, "49d926be-ecee-4575-b013-6612d4c32a59");
                _assigntoadministrator_btnInfo = new RepoItemInfo(this, "AssignToAdministrator_Btn", ".//button[#'ShowAssignToAdminDialog']", ".//button[#'ShowAssignToAdminDialog']", 30000, null, "2fc760b5-ed34-4113-8f26-1426847ef9e6");
                _assign_dialog_select_btnInfo = new RepoItemInfo(this, "Assign_Dialog_Select_Btn", ".//div[#'DivSelectAssignedToAdminDialog']//button[@innertext~'Select']", ".//div[#'DivSelectAssignedToAdminDialog']//button[@innertext='    Select']", 30000, null, "f372c188-61a2-4370-9c22-0e18cfe0e412");
                _assignprompt_yes_btnInfo = new RepoItemInfo(this, "AssignPrompt_Yes_Btn", "body/div[58]/div[3]/div/button[@innertext='Yes']", "body/div[58]/div[3]/div/button[@innertext='Yes']", 30000, null, "8ddf4bf1-8dac-4cd6-9914-56d0657e7bac");
                _assignsuccessful_ok_btnInfo = new RepoItemInfo(this, "AssignSuccessful_Ok_Btn", "body/div[60]/div[3]/div/button[@innertext='Ok']", "body/div[60]/div[3]/div/button[@innertext='Ok']", 30000, null, "db7e23fa-1d58-416c-9ab1-aaf1a6c744f6");
                _activitydetails_assignedtoadminnameInfo = new RepoItemInfo(this, "ActivityDetails_AssignedToAdminName", ".//div[#'DivAssignedToAdminName']", ".//div[#'DivAssignedToAdminName']", 30000, null, "ee9e598c-edeb-4a7b-a582-022ee5be906a");
                _activites_activitydetailstabInfo = new RepoItemInfo(this, "Activites_ActivityDetailsTab", ".//div[#'DivTabPanelsCollection']//a[@innertext='Activity Details']", ".//div[#'DivTabPanelsCollection']//a[@innertext='Activity Details']", 30000, null, "19205d7c-7c67-4d0c-b099-4b5b1186b94d");
                _activities_resultssummarytabInfo = new RepoItemInfo(this, "Activities_ResultsSummaryTab", ".//div[#'DivTabPanelsCollection']//a[@innertext='Results Summary']", ".//div[#'DivTabPanelsCollection']//a[@innertext='Results Summary']", 30000, null, "3cb79990-70fe-4db1-8889-8ecbfe4307c2");
                _resultssummarytab_approve_btnInfo = new RepoItemInfo(this, "ResultsSummaryTab_Approve_Btn", ".//button[#'DoApprove']", ".//button[#'DoApprove']", 30000, null, "e0e4ae25-a8ec-498a-aea0-bafa03251861");
                _approveactivity_modal_continue_btnInfo = new RepoItemInfo(this, "ApproveActivity_Modal_Continue_Btn", "body/div[25]/div[3]/div/button[@innertext='Continue']", "body/div[25]/div[3]/div/button[@innertext='Continue']", 30000, null, "c6fcce01-f791-4067-b8bc-ea29b612a07e");
                _activityhasbeenapproved_ok_btnInfo = new RepoItemInfo(this, "ActivityHasBeenApproved_OK_Btn", ".//button[@innertext='OK']", ".//button[@innertext='OK']", 30000, null, "8e90b798-a591-430c-9a44-5f5bc9027520");
                _activitystatusfieldstatusidInfo = new RepoItemInfo(this, "ActivityStatusFieldStatusID", ".//select[#'ActivityStatusField_StatusID']", ".//select[#'ActivityStatusField_StatusID']", 30000, null, "5b5d1687-8ea6-4263-a4cf-7d3c6115bb45");
                _activitydetails_activitystatusfield_readyfordistributionInfo = new RepoItemInfo(this, "ActivityDetails_ActivityStatusField_ReadyForDistribution", ".//select[#'ActivityStatusField_StatusID']/option[@value>'9abfb684-c9ec-4fe0-8efd-1']", ".//select[#'ActivityStatusField_StatusID']/option[@value>'9abfb684-c9ec-4fe0-8efd-1']", 30000, null, "4144493c-3c11-4c2d-a880-a45f8e530053");
                _activitydetails_activitystatusfield_distributedInfo = new RepoItemInfo(this, "ActivityDetails_ActivityStatusField_Distributed", ".//select[#'ActivityStatusField_StatusID']/option[@value>'795f3755-fbec-4fe3-86b3-5']", ".//select[#'ActivityStatusField_StatusID']/option[@value>'795f3755-fbec-4fe3-86b3-5']", 30000, null, "f6822a78-cf54-403e-83a8-f6faa0501fde");
                _resultssummarytab_distribute_btnInfo = new RepoItemInfo(this, "ResultsSummaryTab_Distribute_Btn", ".//div[#'DivTabPanelResultsSummary']//button[@innertext='Distribute']", ".//div[#'DivTabPanelResultsSummary']//button[@innertext='Distribute']", 30000, null, "e2421ef7-9ba9-47ed-a009-f62777a25969");
                _selectreportrecipients_ok_btn_64Info = new RepoItemInfo(this, "SelectReportRecipients_Ok_Btn_64", "body/div[64]/div[3]/div/button[@innertext='Ok']", "body/div[64]/div[3]/div/button[@innertext='Ok']", 1000, null, "d8178d75-e382-4078-914f-7fff92d3a86f");
                _selectreportrecipients_ok_btn_66Info = new RepoItemInfo(this, "SelectReportRecipients_Ok_Btn_66", "body/div[66]/div[3]/div/button[@innertext='Ok']", "body/div[64]/div[3]/div/button[@innertext='Ok']", 1000, null, "1fdd635c-ea6e-42e9-bed2-b122525e8af5");
                _confirmemailtobesent_send_btnInfo = new RepoItemInfo(this, "ConfirmEmailToBeSent_Send_Btn", ".//button[@innertext='Send']", ".//button[@innertext='Send']", 30000, null, "8d852439-918f-4e87-ad0e-17f6e606833c");
                _emailconfirmation_ok_btn_72Info = new RepoItemInfo(this, "EmailConfirmation_Ok_Btn_72", "body/div[72]/div[3]/div/button[@innertext='Ok']", "", 1000, null, "c51bc5a6-9229-4245-8e06-5a234857ffec");
                _emailconfirmation_ok_btn_73Info = new RepoItemInfo(this, "EmailConfirmation_Ok_Btn_73", "body/div[73]/div[3]/div/button[@innertext='Ok']", "body/div[74]/div[3]/div/button[@innertext='Ok']", 1000, null, "3188aa73-6021-4bf2-8cc0-8501f00fa34d");
                _emailconfirmation_ok_btn_74Info = new RepoItemInfo(this, "EmailConfirmation_Ok_Btn_74", "body/div[74]/div[3]/div/button[@innertext='Ok']", "body/div[74]/div[3]/div/button[@innertext='Ok']", 1000, null, "654d7145-c41b-4a53-ac16-b8c5fcc9fcdf");
                _activitysearchresults_activityid_row1Info = new RepoItemInfo(this, "ActivitySearchResults_ActivityID_Row1", ".//table[#'MaintainActivitiesGrid']/tbody/tr[1]/td[2]", ".//table[#'MaintainActivitiesGrid']//td[@innertext>'         2400000111']", 30000, null, "2cbd688c-95a1-4f5a-a7ac-c0a3225a1d1d");
                _activityuniqueiddisplayvalueInfo = new RepoItemInfo(this, "ActivityUniqueIDDisplayValue", ".//input[#'ActivityUniqueID_DisplayValue']", ".//input[#'ActivityUniqueID_DisplayValue']", 30000, null, "d22a01ee-7ded-47a6-b88a-779dab1ae642");
                _activitydetailstab_client_textInfo = new RepoItemInfo(this, "ActivityDetailsTab_Client_Text", ".//div[#'DivTabPanelActivityDetails']//legend[@innertext='Client']", ".//div[#'DivTabPanelActivityDetails']//legend[@innertext='Client']", 30000, null, "0f619561-408d-4f9d-a21b-2266f0cdba01");
                _usersearch_results_edit_btn_row1Info = new RepoItemInfo(this, "UserSearch_Results_Edit_Btn_Row1", ".//table[#'MaintainUsersSearchGrid']//button[@innertext~'Edit']", ".//table[#'MaintainUsersSearchGrid']//button[@innertext='    Edit']", 30000, null, "112a63b6-0d37-4d93-8e1f-45faaf00ba82");
                _internaluser_isactiveInfo = new RepoItemInfo(this, "InternalUser_IsActive", ".//input[#'IsActive']", ".//input[#'IsActive']", 30000, null, "b17a8a53-db8e-461a-813d-ede3bb00338f");
                _internaluser_save_btnInfo = new RepoItemInfo(this, "InternalUser_Save_Btn", ".//form[#'form0']/?/?/input[@type='submit']", ".//form[#'form0']/?/?/input[@type='submit']", 1000, null, "0d7d4dda-b1fc-45d1-bad1-ab4591dac13e");
                _externaluser_save_btnInfo = new RepoItemInfo(this, "ExternalUser_Save_Btn", ".//div[#'divFirstColumn']//input[@type='submit']", ".//div[#'divFirstColumn']//input[@type='submit']", 1000, null, "c3c70855-415a-4edb-a140-077e6c178218");
                _consultantportaluserInfo = new RepoItemInfo(this, "ConsultantPortalUser", ".//input[#'ConsultantPortalUser']", ".//input[#'ConsultantPortalUser']", 30000, null, "8f27910d-c91a-407c-af82-8c3109a8378a");
                _loginwasunsuccessfulpleasecorrecttInfo = new RepoItemInfo(this, "LoginWasUnsuccessfulPleaseCorrectT", ".//div[#'validationSummary']/span[@innertext>'Login was unsuccessful. Please']", ".//div[#'validationSummary']/span[@innertext>'Login was unsuccessful. Please']", 30000, null, "6b3ba1de-6afc-4a82-9072-e53ff3208f5b");
                _customerportalclass_combined_checkboxInfo = new RepoItemInfo(this, "CustomerPortalClass_Combined_Checkbox", ".//div[#'divCustomerPortalClasses']/input[@name='CustomerPortalClasses[0].Selected' and @type='checkbox']", ".//div[#'divCustomerPortalClasses']/input[@name='CustomerPortalClasses[0].Selected' and @type='checkbox']", 30000, null, "747cdd3c-27f4-4c21-b13f-6f443270fdfb");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("caa3c3ad-7fc6-453d-b4c8-aab07fd99cb5")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("caa3c3ad-7fc6-453d-b4c8-aab07fd99cb5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The UserName item.
            /// </summary>
            [RepositoryItem("d1498fdd-de77-47d0-9590-24ab7d1761d2")]
            public virtual Ranorex.InputTag UserName
            {
                get
                {
                    return _usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The UserName item info.
            /// </summary>
            [RepositoryItemInfo("d1498fdd-de77-47d0-9590-24ab7d1761d2")]
            public virtual RepoItemInfo UserNameInfo
            {
                get
                {
                    return _usernameInfo;
                }
            }

            /// <summary>
            /// The Password item.
            /// </summary>
            [RepositoryItem("64cf3923-cb84-44ca-bc4d-7b670d0a9f94")]
            public virtual Ranorex.InputTag Password
            {
                get
                {
                    return _passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Password item info.
            /// </summary>
            [RepositoryItemInfo("64cf3923-cb84-44ca-bc4d-7b670d0a9f94")]
            public virtual RepoItemInfo PasswordInfo
            {
                get
                {
                    return _passwordInfo;
                }
            }

            /// <summary>
            /// The LogIn_Btn item.
            /// </summary>
            [RepositoryItem("3f88cce4-08cf-41e9-8e6f-93920710942c")]
            public virtual Ranorex.ButtonTag LogIn_Btn
            {
                get
                {
                    return _login_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The LogIn_Btn item info.
            /// </summary>
            [RepositoryItemInfo("3f88cce4-08cf-41e9-8e6f-93920710942c")]
            public virtual RepoItemInfo LogIn_BtnInfo
            {
                get
                {
                    return _login_btnInfo;
                }
            }

            /// <summary>
            /// The AdminMenuListItem item.
            /// </summary>
            [RepositoryItem("64a436d5-db7d-4805-b18e-eab529cbeed6")]
            public virtual Ranorex.LiTag AdminMenuListItem
            {
                get
                {
                    return _adminmenulistitemInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The AdminMenuListItem item info.
            /// </summary>
            [RepositoryItemInfo("64a436d5-db7d-4805-b18e-eab529cbeed6")]
            public virtual RepoItemInfo AdminMenuListItemInfo
            {
                get
                {
                    return _adminmenulistitemInfo;
                }
            }

            /// <summary>
            /// The Users item.
            /// </summary>
            [RepositoryItem("d2567940-c044-4d5a-b8b4-d7a58def3de7")]
            public virtual Ranorex.ATag Users
            {
                get
                {
                    return _usersInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Users item info.
            /// </summary>
            [RepositoryItemInfo("d2567940-c044-4d5a-b8b4-d7a58def3de7")]
            public virtual RepoItemInfo UsersInfo
            {
                get
                {
                    return _usersInfo;
                }
            }

            /// <summary>
            /// The SurnameDisplayValue item.
            /// </summary>
            [RepositoryItem("17fde772-4b8d-4fde-959b-053ce6e6a6e3")]
            public virtual Ranorex.InputTag SurnameDisplayValue
            {
                get
                {
                    return _surnamedisplayvalueInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SurnameDisplayValue item info.
            /// </summary>
            [RepositoryItemInfo("17fde772-4b8d-4fde-959b-053ce6e6a6e3")]
            public virtual RepoItemInfo SurnameDisplayValueInfo
            {
                get
                {
                    return _surnamedisplayvalueInfo;
                }
            }

            /// <summary>
            /// The AddInternalButton item.
            /// </summary>
            [RepositoryItem("1e720a3c-cfdb-4341-bec3-dfc476edac00")]
            public virtual Ranorex.ButtonTag AddInternalButton
            {
                get
                {
                    return _addinternalbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddInternalButton item info.
            /// </summary>
            [RepositoryItemInfo("1e720a3c-cfdb-4341-bec3-dfc476edac00")]
            public virtual RepoItemInfo AddInternalButtonInfo
            {
                get
                {
                    return _addinternalbuttonInfo;
                }
            }

            /// <summary>
            /// The InternalUser_Username item.
            /// </summary>
            [RepositoryItem("b0c3725a-df5e-4197-98b4-3826f861361f")]
            public virtual Ranorex.InputTag InternalUser_Username
            {
                get
                {
                    return _internaluser_usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InternalUser_Username item info.
            /// </summary>
            [RepositoryItemInfo("b0c3725a-df5e-4197-98b4-3826f861361f")]
            public virtual RepoItemInfo InternalUser_UsernameInfo
            {
                get
                {
                    return _internaluser_usernameInfo;
                }
            }

            /// <summary>
            /// The Loading_Modal item.
            /// </summary>
            [RepositoryItem("cac4c031-4424-462c-a4bb-5b56bc87801a")]
            public virtual Ranorex.DivTag Loading_Modal
            {
                get
                {
                    return _loading_modalInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Loading_Modal item info.
            /// </summary>
            [RepositoryItemInfo("cac4c031-4424-462c-a4bb-5b56bc87801a")]
            public virtual RepoItemInfo Loading_ModalInfo
            {
                get
                {
                    return _loading_modalInfo;
                }
            }

            /// <summary>
            /// The UserMenuItem item.
            /// </summary>
            [RepositoryItem("1cf6717f-18cc-4c90-8ee5-c55bd8c53aff")]
            public virtual Ranorex.ATag UserMenuItem
            {
                get
                {
                    return _usermenuitemInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The UserMenuItem item info.
            /// </summary>
            [RepositoryItemInfo("1cf6717f-18cc-4c90-8ee5-c55bd8c53aff")]
            public virtual RepoItemInfo UserMenuItemInfo
            {
                get
                {
                    return _usermenuitemInfo;
                }
            }

            /// <summary>
            /// The UserMenuItem_LogoutButton item.
            /// </summary>
            [RepositoryItem("dbe6ead6-f226-45b0-949d-11fd02bcbfd6")]
            public virtual Ranorex.ATag UserMenuItem_LogoutButton
            {
                get
                {
                    return _usermenuitem_logoutbuttonInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The UserMenuItem_LogoutButton item info.
            /// </summary>
            [RepositoryItemInfo("dbe6ead6-f226-45b0-949d-11fd02bcbfd6")]
            public virtual RepoItemInfo UserMenuItem_LogoutButtonInfo
            {
                get
                {
                    return _usermenuitem_logoutbuttonInfo;
                }
            }

            /// <summary>
            /// The Logout_Btn item.
            /// </summary>
            [RepositoryItem("7684af78-3847-4a5a-90fa-6692227abda4")]
            public virtual Ranorex.ButtonTag Logout_Btn
            {
                get
                {
                    return _logout_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Logout_Btn item info.
            /// </summary>
            [RepositoryItemInfo("7684af78-3847-4a5a-90fa-6692227abda4")]
            public virtual RepoItemInfo Logout_BtnInfo
            {
                get
                {
                    return _logout_btnInfo;
                }
            }

            /// <summary>
            /// The RequestsMenuItem item.
            /// </summary>
            [RepositoryItem("62f9f025-d766-4860-b39f-54a8b7158b31")]
            public virtual Ranorex.ATag RequestsMenuItem
            {
                get
                {
                    return _requestsmenuitemInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The RequestsMenuItem item info.
            /// </summary>
            [RepositoryItemInfo("62f9f025-d766-4860-b39f-54a8b7158b31")]
            public virtual RepoItemInfo RequestsMenuItemInfo
            {
                get
                {
                    return _requestsmenuitemInfo;
                }
            }

            /// <summary>
            /// The NewRequest item.
            /// </summary>
            [RepositoryItem("addbd8b8-86ee-4ae1-b158-9ab2b841b65e")]
            public virtual Ranorex.ATag NewRequest
            {
                get
                {
                    return _newrequestInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The NewRequest item info.
            /// </summary>
            [RepositoryItemInfo("addbd8b8-86ee-4ae1-b158-9ab2b841b65e")]
            public virtual RepoItemInfo NewRequestInfo
            {
                get
                {
                    return _newrequestInfo;
                }
            }

            /// <summary>
            /// The HomeMenuItem item.
            /// </summary>
            [RepositoryItem("807d55bb-c583-48f1-ac75-3d442fc93929")]
            public virtual Ranorex.ATag HomeMenuItem
            {
                get
                {
                    return _homemenuitemInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The HomeMenuItem item info.
            /// </summary>
            [RepositoryItemInfo("807d55bb-c583-48f1-ac75-3d442fc93929")]
            public virtual RepoItemInfo HomeMenuItemInfo
            {
                get
                {
                    return _homemenuitemInfo;
                }
            }

            /// <summary>
            /// The ClientSearch_Name item.
            /// </summary>
            [RepositoryItem("7b7cc824-db48-492f-8535-436f77c1590a")]
            public virtual Ranorex.InputTag ClientSearch_Name
            {
                get
                {
                    return _clientsearch_nameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ClientSearch_Name item info.
            /// </summary>
            [RepositoryItemInfo("7b7cc824-db48-492f-8535-436f77c1590a")]
            public virtual RepoItemInfo ClientSearch_NameInfo
            {
                get
                {
                    return _clientsearch_nameInfo;
                }
            }

            /// <summary>
            /// The ClientName_ZZTestEnergyCompany item.
            /// </summary>
            [RepositoryItem("c9ac06db-3d12-4757-bd9c-bc64240a96a9")]
            public virtual Ranorex.DivTag ClientName_ZZTestEnergyCompany
            {
                get
                {
                    return _clientname_zztestenergycompanyInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ClientName_ZZTestEnergyCompany item info.
            /// </summary>
            [RepositoryItemInfo("c9ac06db-3d12-4757-bd9c-bc64240a96a9")]
            public virtual RepoItemInfo ClientName_ZZTestEnergyCompanyInfo
            {
                get
                {
                    return _clientname_zztestenergycompanyInfo;
                }
            }

            /// <summary>
            /// The NewMultiActivityRequestHeaderText item.
            /// </summary>
            [RepositoryItem("0e0d44c1-bf64-4f3a-920b-6cc40d9f40c2")]
            public virtual Ranorex.LegendTag NewMultiActivityRequestHeaderText
            {
                get
                {
                    return _newmultiactivityrequestheadertextInfo.CreateAdapter<Ranorex.LegendTag>(true);
                }
            }

            /// <summary>
            /// The NewMultiActivityRequestHeaderText item info.
            /// </summary>
            [RepositoryItemInfo("0e0d44c1-bf64-4f3a-920b-6cc40d9f40c2")]
            public virtual RepoItemInfo NewMultiActivityRequestHeaderTextInfo
            {
                get
                {
                    return _newmultiactivityrequestheadertextInfo;
                }
            }

            /// <summary>
            /// The NewMultiActivityRequest_ClassPolicy_Select item.
            /// </summary>
            [RepositoryItem("016cdfc3-e21f-4ab8-94c9-bac9d8b67873")]
            public virtual Ranorex.SelectTag NewMultiActivityRequest_ClassPolicy_Select
            {
                get
                {
                    return _newmultiactivityrequest_classpolicy_selectInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The NewMultiActivityRequest_ClassPolicy_Select item info.
            /// </summary>
            [RepositoryItemInfo("016cdfc3-e21f-4ab8-94c9-bac9d8b67873")]
            public virtual RepoItemInfo NewMultiActivityRequest_ClassPolicy_SelectInfo
            {
                get
                {
                    return _newmultiactivityrequest_classpolicy_selectInfo;
                }
            }

            /// <summary>
            /// The NewMultiActivityRequest_Policy_PRO000452025_Utility item.
            /// </summary>
            [RepositoryItem("8f36980c-7956-4ee3-a982-9234fca0f44d")]
            public virtual Ranorex.OptionTag NewMultiActivityRequest_Policy_PRO000452025_Utility
            {
                get
                {
                    return _newmultiactivityrequest_policy_pro000452025_utilityInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The NewMultiActivityRequest_Policy_PRO000452025_Utility item info.
            /// </summary>
            [RepositoryItemInfo("8f36980c-7956-4ee3-a982-9234fca0f44d")]
            public virtual RepoItemInfo NewMultiActivityRequest_Policy_PRO000452025_UtilityInfo
            {
                get
                {
                    return _newmultiactivityrequest_policy_pro000452025_utilityInfo;
                }
            }

            /// <summary>
            /// The NewMultiActivityRequest_Policy_PRO000462021_Property item.
            /// </summary>
            [RepositoryItem("67d00a5f-3d07-4e3f-8ba3-89918909e957")]
            public virtual Ranorex.OptionTag NewMultiActivityRequest_Policy_PRO000462021_Property
            {
                get
                {
                    return _newmultiactivityrequest_policy_pro000462021_propertyInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The NewMultiActivityRequest_Policy_PRO000462021_Property item info.
            /// </summary>
            [RepositoryItemInfo("67d00a5f-3d07-4e3f-8ba3-89918909e957")]
            public virtual RepoItemInfo NewMultiActivityRequest_Policy_PRO000462021_PropertyInfo
            {
                get
                {
                    return _newmultiactivityrequest_policy_pro000462021_propertyInfo;
                }
            }

            /// <summary>
            /// The NewMultiActivityRequest_ActivityType_Select item.
            /// </summary>
            [RepositoryItem("a2747e2b-fadc-4d86-8c39-a87d5350e11c")]
            public virtual Ranorex.SelectTag NewMultiActivityRequest_ActivityType_Select
            {
                get
                {
                    return _newmultiactivityrequest_activitytype_selectInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The NewMultiActivityRequest_ActivityType_Select item info.
            /// </summary>
            [RepositoryItemInfo("a2747e2b-fadc-4d86-8c39-a87d5350e11c")]
            public virtual RepoItemInfo NewMultiActivityRequest_ActivityType_SelectInfo
            {
                get
                {
                    return _newmultiactivityrequest_activitytype_selectInfo;
                }
            }

            /// <summary>
            /// The NewMultiActivityRequest_ActivityType_Select_RiskAssessment item.
            /// </summary>
            [RepositoryItem("d6741907-8f3f-4dc3-8133-102bd999b60d")]
            public virtual Ranorex.OptionTag NewMultiActivityRequest_ActivityType_Select_RiskAssessment
            {
                get
                {
                    return _newmultiactivityrequest_activitytype_select_riskassessmentInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The NewMultiActivityRequest_ActivityType_Select_RiskAssessment item info.
            /// </summary>
            [RepositoryItemInfo("d6741907-8f3f-4dc3-8133-102bd999b60d")]
            public virtual RepoItemInfo NewMultiActivityRequest_ActivityType_Select_RiskAssessmentInfo
            {
                get
                {
                    return _newmultiactivityrequest_activitytype_select_riskassessmentInfo;
                }
            }

            /// <summary>
            /// The NewMultiActivityRequest_Focus_Select item.
            /// </summary>
            [RepositoryItem("656798f4-48c1-429c-8a37-c415e2bd51df")]
            public virtual Ranorex.SelectTag NewMultiActivityRequest_Focus_Select
            {
                get
                {
                    return _newmultiactivityrequest_focus_selectInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The NewMultiActivityRequest_Focus_Select item info.
            /// </summary>
            [RepositoryItemInfo("656798f4-48c1-429c-8a37-c415e2bd51df")]
            public virtual RepoItemInfo NewMultiActivityRequest_Focus_SelectInfo
            {
                get
                {
                    return _newmultiactivityrequest_focus_selectInfo;
                }
            }

            /// <summary>
            /// The NewMultiActivityRequest_Engineer item.
            /// </summary>
            [RepositoryItem("41ee6a97-5758-4c8e-99dd-d82abf42a55b")]
            public virtual Ranorex.SelectTag NewMultiActivityRequest_Engineer
            {
                get
                {
                    return _newmultiactivityrequest_engineerInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The NewMultiActivityRequest_Engineer item info.
            /// </summary>
            [RepositoryItemInfo("41ee6a97-5758-4c8e-99dd-d82abf42a55b")]
            public virtual RepoItemInfo NewMultiActivityRequest_EngineerInfo
            {
                get
                {
                    return _newmultiactivityrequest_engineerInfo;
                }
            }

            /// <summary>
            /// The SubmitRequest_Btn item.
            /// </summary>
            [RepositoryItem("5f57dadf-4ba2-4fe5-9efa-410d4034f258")]
            public virtual Ranorex.InputTag SubmitRequest_Btn
            {
                get
                {
                    return _submitrequest_btnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The SubmitRequest_Btn item info.
            /// </summary>
            [RepositoryItemInfo("5f57dadf-4ba2-4fe5-9efa-410d4034f258")]
            public virtual RepoItemInfo SubmitRequest_BtnInfo
            {
                get
                {
                    return _submitrequest_btnInfo;
                }
            }

            /// <summary>
            /// The SuccessMessages item.
            /// </summary>
            [RepositoryItem("9dabedb3-db57-4a83-98dd-d2491b9ff4fd")]
            public virtual Ranorex.DivTag SuccessMessages
            {
                get
                {
                    return _successmessagesInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The SuccessMessages item info.
            /// </summary>
            [RepositoryItemInfo("9dabedb3-db57-4a83-98dd-d2491b9ff4fd")]
            public virtual RepoItemInfo SuccessMessagesInfo
            {
                get
                {
                    return _successmessagesInfo;
                }
            }

            /// <summary>
            /// The ActivitySearch_Search_Btn item.
            /// </summary>
            [RepositoryItem("731702ee-6d96-4549-a1ce-c2b2a42fd7d0")]
            public virtual Ranorex.InputTag ActivitySearch_Search_Btn
            {
                get
                {
                    return _activitysearch_search_btnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ActivitySearch_Search_Btn item info.
            /// </summary>
            [RepositoryItemInfo("731702ee-6d96-4549-a1ce-c2b2a42fd7d0")]
            public virtual RepoItemInfo ActivitySearch_Search_BtnInfo
            {
                get
                {
                    return _activitysearch_search_btnInfo;
                }
            }

            /// <summary>
            /// The ActivitySearch_Results_Text item.
            /// </summary>
            [RepositoryItem("be6740ea-f568-452d-96e7-a0fe20ba7a74")]
            public virtual Ranorex.LegendTag ActivitySearch_Results_Text
            {
                get
                {
                    return _activitysearch_results_textInfo.CreateAdapter<Ranorex.LegendTag>(true);
                }
            }

            /// <summary>
            /// The ActivitySearch_Results_Text item info.
            /// </summary>
            [RepositoryItemInfo("be6740ea-f568-452d-96e7-a0fe20ba7a74")]
            public virtual RepoItemInfo ActivitySearch_Results_TextInfo
            {
                get
                {
                    return _activitysearch_results_textInfo;
                }
            }

            /// <summary>
            /// The ResultsGrid_Select_Btn_Row1 item.
            /// </summary>
            [RepositoryItem("49d926be-ecee-4575-b013-6612d4c32a59")]
            public virtual Ranorex.ButtonTag ResultsGrid_Select_Btn_Row1
            {
                get
                {
                    return _resultsgrid_select_btn_row1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ResultsGrid_Select_Btn_Row1 item info.
            /// </summary>
            [RepositoryItemInfo("49d926be-ecee-4575-b013-6612d4c32a59")]
            public virtual RepoItemInfo ResultsGrid_Select_Btn_Row1Info
            {
                get
                {
                    return _resultsgrid_select_btn_row1Info;
                }
            }

            /// <summary>
            /// The AssignToAdministrator_Btn item.
            /// </summary>
            [RepositoryItem("2fc760b5-ed34-4113-8f26-1426847ef9e6")]
            public virtual Ranorex.ButtonTag AssignToAdministrator_Btn
            {
                get
                {
                    return _assigntoadministrator_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AssignToAdministrator_Btn item info.
            /// </summary>
            [RepositoryItemInfo("2fc760b5-ed34-4113-8f26-1426847ef9e6")]
            public virtual RepoItemInfo AssignToAdministrator_BtnInfo
            {
                get
                {
                    return _assigntoadministrator_btnInfo;
                }
            }

            /// <summary>
            /// The Assign_Dialog_Select_Btn item.
            /// </summary>
            [RepositoryItem("f372c188-61a2-4370-9c22-0e18cfe0e412")]
            public virtual Ranorex.ButtonTag Assign_Dialog_Select_Btn
            {
                get
                {
                    return _assign_dialog_select_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Assign_Dialog_Select_Btn item info.
            /// </summary>
            [RepositoryItemInfo("f372c188-61a2-4370-9c22-0e18cfe0e412")]
            public virtual RepoItemInfo Assign_Dialog_Select_BtnInfo
            {
                get
                {
                    return _assign_dialog_select_btnInfo;
                }
            }

            /// <summary>
            /// The AssignPrompt_Yes_Btn item.
            /// </summary>
            [RepositoryItem("8ddf4bf1-8dac-4cd6-9914-56d0657e7bac")]
            public virtual Ranorex.ButtonTag AssignPrompt_Yes_Btn
            {
                get
                {
                    return _assignprompt_yes_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AssignPrompt_Yes_Btn item info.
            /// </summary>
            [RepositoryItemInfo("8ddf4bf1-8dac-4cd6-9914-56d0657e7bac")]
            public virtual RepoItemInfo AssignPrompt_Yes_BtnInfo
            {
                get
                {
                    return _assignprompt_yes_btnInfo;
                }
            }

            /// <summary>
            /// The AssignSuccessful_Ok_Btn item.
            /// </summary>
            [RepositoryItem("db7e23fa-1d58-416c-9ab1-aaf1a6c744f6")]
            public virtual Ranorex.ButtonTag AssignSuccessful_Ok_Btn
            {
                get
                {
                    return _assignsuccessful_ok_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AssignSuccessful_Ok_Btn item info.
            /// </summary>
            [RepositoryItemInfo("db7e23fa-1d58-416c-9ab1-aaf1a6c744f6")]
            public virtual RepoItemInfo AssignSuccessful_Ok_BtnInfo
            {
                get
                {
                    return _assignsuccessful_ok_btnInfo;
                }
            }

            /// <summary>
            /// The ActivityDetails_AssignedToAdminName item.
            /// </summary>
            [RepositoryItem("ee9e598c-edeb-4a7b-a582-022ee5be906a")]
            public virtual Ranorex.DivTag ActivityDetails_AssignedToAdminName
            {
                get
                {
                    return _activitydetails_assignedtoadminnameInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The ActivityDetails_AssignedToAdminName item info.
            /// </summary>
            [RepositoryItemInfo("ee9e598c-edeb-4a7b-a582-022ee5be906a")]
            public virtual RepoItemInfo ActivityDetails_AssignedToAdminNameInfo
            {
                get
                {
                    return _activitydetails_assignedtoadminnameInfo;
                }
            }

            /// <summary>
            /// The Activites_ActivityDetailsTab item.
            /// </summary>
            [RepositoryItem("19205d7c-7c67-4d0c-b099-4b5b1186b94d")]
            public virtual Ranorex.ATag Activites_ActivityDetailsTab
            {
                get
                {
                    return _activites_activitydetailstabInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Activites_ActivityDetailsTab item info.
            /// </summary>
            [RepositoryItemInfo("19205d7c-7c67-4d0c-b099-4b5b1186b94d")]
            public virtual RepoItemInfo Activites_ActivityDetailsTabInfo
            {
                get
                {
                    return _activites_activitydetailstabInfo;
                }
            }

            /// <summary>
            /// The Activities_ResultsSummaryTab item.
            /// </summary>
            [RepositoryItem("3cb79990-70fe-4db1-8889-8ecbfe4307c2")]
            public virtual Ranorex.ATag Activities_ResultsSummaryTab
            {
                get
                {
                    return _activities_resultssummarytabInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Activities_ResultsSummaryTab item info.
            /// </summary>
            [RepositoryItemInfo("3cb79990-70fe-4db1-8889-8ecbfe4307c2")]
            public virtual RepoItemInfo Activities_ResultsSummaryTabInfo
            {
                get
                {
                    return _activities_resultssummarytabInfo;
                }
            }

            /// <summary>
            /// The ResultsSummaryTab_Approve_Btn item.
            /// </summary>
            [RepositoryItem("e0e4ae25-a8ec-498a-aea0-bafa03251861")]
            public virtual Ranorex.ButtonTag ResultsSummaryTab_Approve_Btn
            {
                get
                {
                    return _resultssummarytab_approve_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ResultsSummaryTab_Approve_Btn item info.
            /// </summary>
            [RepositoryItemInfo("e0e4ae25-a8ec-498a-aea0-bafa03251861")]
            public virtual RepoItemInfo ResultsSummaryTab_Approve_BtnInfo
            {
                get
                {
                    return _resultssummarytab_approve_btnInfo;
                }
            }

            /// <summary>
            /// The ApproveActivity_Modal_Continue_Btn item.
            /// </summary>
            [RepositoryItem("c6fcce01-f791-4067-b8bc-ea29b612a07e")]
            public virtual Ranorex.ButtonTag ApproveActivity_Modal_Continue_Btn
            {
                get
                {
                    return _approveactivity_modal_continue_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ApproveActivity_Modal_Continue_Btn item info.
            /// </summary>
            [RepositoryItemInfo("c6fcce01-f791-4067-b8bc-ea29b612a07e")]
            public virtual RepoItemInfo ApproveActivity_Modal_Continue_BtnInfo
            {
                get
                {
                    return _approveactivity_modal_continue_btnInfo;
                }
            }

            /// <summary>
            /// The ActivityHasBeenApproved_OK_Btn item.
            /// </summary>
            [RepositoryItem("8e90b798-a591-430c-9a44-5f5bc9027520")]
            public virtual Ranorex.ButtonTag ActivityHasBeenApproved_OK_Btn
            {
                get
                {
                    return _activityhasbeenapproved_ok_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ActivityHasBeenApproved_OK_Btn item info.
            /// </summary>
            [RepositoryItemInfo("8e90b798-a591-430c-9a44-5f5bc9027520")]
            public virtual RepoItemInfo ActivityHasBeenApproved_OK_BtnInfo
            {
                get
                {
                    return _activityhasbeenapproved_ok_btnInfo;
                }
            }

            /// <summary>
            /// The ActivityStatusFieldStatusID item.
            /// </summary>
            [RepositoryItem("5b5d1687-8ea6-4263-a4cf-7d3c6115bb45")]
            public virtual Ranorex.SelectTag ActivityStatusFieldStatusID
            {
                get
                {
                    return _activitystatusfieldstatusidInfo.CreateAdapter<Ranorex.SelectTag>(true);
                }
            }

            /// <summary>
            /// The ActivityStatusFieldStatusID item info.
            /// </summary>
            [RepositoryItemInfo("5b5d1687-8ea6-4263-a4cf-7d3c6115bb45")]
            public virtual RepoItemInfo ActivityStatusFieldStatusIDInfo
            {
                get
                {
                    return _activitystatusfieldstatusidInfo;
                }
            }

            /// <summary>
            /// The ActivityDetails_ActivityStatusField_ReadyForDistribution item.
            /// </summary>
            [RepositoryItem("4144493c-3c11-4c2d-a880-a45f8e530053")]
            public virtual Ranorex.OptionTag ActivityDetails_ActivityStatusField_ReadyForDistribution
            {
                get
                {
                    return _activitydetails_activitystatusfield_readyfordistributionInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The ActivityDetails_ActivityStatusField_ReadyForDistribution item info.
            /// </summary>
            [RepositoryItemInfo("4144493c-3c11-4c2d-a880-a45f8e530053")]
            public virtual RepoItemInfo ActivityDetails_ActivityStatusField_ReadyForDistributionInfo
            {
                get
                {
                    return _activitydetails_activitystatusfield_readyfordistributionInfo;
                }
            }

            /// <summary>
            /// The ActivityDetails_ActivityStatusField_Distributed item.
            /// </summary>
            [RepositoryItem("f6822a78-cf54-403e-83a8-f6faa0501fde")]
            public virtual Ranorex.OptionTag ActivityDetails_ActivityStatusField_Distributed
            {
                get
                {
                    return _activitydetails_activitystatusfield_distributedInfo.CreateAdapter<Ranorex.OptionTag>(true);
                }
            }

            /// <summary>
            /// The ActivityDetails_ActivityStatusField_Distributed item info.
            /// </summary>
            [RepositoryItemInfo("f6822a78-cf54-403e-83a8-f6faa0501fde")]
            public virtual RepoItemInfo ActivityDetails_ActivityStatusField_DistributedInfo
            {
                get
                {
                    return _activitydetails_activitystatusfield_distributedInfo;
                }
            }

            /// <summary>
            /// The ResultsSummaryTab_Distribute_Btn item.
            /// </summary>
            [RepositoryItem("e2421ef7-9ba9-47ed-a009-f62777a25969")]
            public virtual Ranorex.ButtonTag ResultsSummaryTab_Distribute_Btn
            {
                get
                {
                    return _resultssummarytab_distribute_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ResultsSummaryTab_Distribute_Btn item info.
            /// </summary>
            [RepositoryItemInfo("e2421ef7-9ba9-47ed-a009-f62777a25969")]
            public virtual RepoItemInfo ResultsSummaryTab_Distribute_BtnInfo
            {
                get
                {
                    return _resultssummarytab_distribute_btnInfo;
                }
            }

            /// <summary>
            /// The SelectReportRecipients_Ok_Btn_64 item.
            /// </summary>
            [RepositoryItem("d8178d75-e382-4078-914f-7fff92d3a86f")]
            public virtual Ranorex.ButtonTag SelectReportRecipients_Ok_Btn_64
            {
                get
                {
                    return _selectreportrecipients_ok_btn_64Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SelectReportRecipients_Ok_Btn_64 item info.
            /// </summary>
            [RepositoryItemInfo("d8178d75-e382-4078-914f-7fff92d3a86f")]
            public virtual RepoItemInfo SelectReportRecipients_Ok_Btn_64Info
            {
                get
                {
                    return _selectreportrecipients_ok_btn_64Info;
                }
            }

            /// <summary>
            /// The SelectReportRecipients_Ok_Btn_66 item.
            /// </summary>
            [RepositoryItem("1fdd635c-ea6e-42e9-bed2-b122525e8af5")]
            public virtual Ranorex.ButtonTag SelectReportRecipients_Ok_Btn_66
            {
                get
                {
                    return _selectreportrecipients_ok_btn_66Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The SelectReportRecipients_Ok_Btn_66 item info.
            /// </summary>
            [RepositoryItemInfo("1fdd635c-ea6e-42e9-bed2-b122525e8af5")]
            public virtual RepoItemInfo SelectReportRecipients_Ok_Btn_66Info
            {
                get
                {
                    return _selectreportrecipients_ok_btn_66Info;
                }
            }

            /// <summary>
            /// The ConfirmEmailToBeSent_Send_Btn item.
            /// </summary>
            [RepositoryItem("8d852439-918f-4e87-ad0e-17f6e606833c")]
            public virtual Ranorex.ButtonTag ConfirmEmailToBeSent_Send_Btn
            {
                get
                {
                    return _confirmemailtobesent_send_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ConfirmEmailToBeSent_Send_Btn item info.
            /// </summary>
            [RepositoryItemInfo("8d852439-918f-4e87-ad0e-17f6e606833c")]
            public virtual RepoItemInfo ConfirmEmailToBeSent_Send_BtnInfo
            {
                get
                {
                    return _confirmemailtobesent_send_btnInfo;
                }
            }

            /// <summary>
            /// The EmailConfirmation_Ok_Btn_72 item.
            /// </summary>
            [RepositoryItem("c51bc5a6-9229-4245-8e06-5a234857ffec")]
            public virtual Ranorex.ButtonTag EmailConfirmation_Ok_Btn_72
            {
                get
                {
                    return _emailconfirmation_ok_btn_72Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The EmailConfirmation_Ok_Btn_72 item info.
            /// </summary>
            [RepositoryItemInfo("c51bc5a6-9229-4245-8e06-5a234857ffec")]
            public virtual RepoItemInfo EmailConfirmation_Ok_Btn_72Info
            {
                get
                {
                    return _emailconfirmation_ok_btn_72Info;
                }
            }

            /// <summary>
            /// The EmailConfirmation_Ok_Btn_73 item.
            /// </summary>
            [RepositoryItem("3188aa73-6021-4bf2-8cc0-8501f00fa34d")]
            public virtual Ranorex.ButtonTag EmailConfirmation_Ok_Btn_73
            {
                get
                {
                    return _emailconfirmation_ok_btn_73Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The EmailConfirmation_Ok_Btn_73 item info.
            /// </summary>
            [RepositoryItemInfo("3188aa73-6021-4bf2-8cc0-8501f00fa34d")]
            public virtual RepoItemInfo EmailConfirmation_Ok_Btn_73Info
            {
                get
                {
                    return _emailconfirmation_ok_btn_73Info;
                }
            }

            /// <summary>
            /// The EmailConfirmation_Ok_Btn_74 item.
            /// </summary>
            [RepositoryItem("654d7145-c41b-4a53-ac16-b8c5fcc9fcdf")]
            public virtual Ranorex.ButtonTag EmailConfirmation_Ok_Btn_74
            {
                get
                {
                    return _emailconfirmation_ok_btn_74Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The EmailConfirmation_Ok_Btn_74 item info.
            /// </summary>
            [RepositoryItemInfo("654d7145-c41b-4a53-ac16-b8c5fcc9fcdf")]
            public virtual RepoItemInfo EmailConfirmation_Ok_Btn_74Info
            {
                get
                {
                    return _emailconfirmation_ok_btn_74Info;
                }
            }

            /// <summary>
            /// The ActivitySearchResults_ActivityID_Row1 item.
            /// </summary>
            [RepositoryItem("2cbd688c-95a1-4f5a-a7ac-c0a3225a1d1d")]
            public virtual Ranorex.TdTag ActivitySearchResults_ActivityID_Row1
            {
                get
                {
                    return _activitysearchresults_activityid_row1Info.CreateAdapter<Ranorex.TdTag>(true);
                }
            }

            /// <summary>
            /// The ActivitySearchResults_ActivityID_Row1 item info.
            /// </summary>
            [RepositoryItemInfo("2cbd688c-95a1-4f5a-a7ac-c0a3225a1d1d")]
            public virtual RepoItemInfo ActivitySearchResults_ActivityID_Row1Info
            {
                get
                {
                    return _activitysearchresults_activityid_row1Info;
                }
            }

            /// <summary>
            /// The ActivityUniqueIDDisplayValue item.
            /// </summary>
            [RepositoryItem("d22a01ee-7ded-47a6-b88a-779dab1ae642")]
            public virtual Ranorex.InputTag ActivityUniqueIDDisplayValue
            {
                get
                {
                    return _activityuniqueiddisplayvalueInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ActivityUniqueIDDisplayValue item info.
            /// </summary>
            [RepositoryItemInfo("d22a01ee-7ded-47a6-b88a-779dab1ae642")]
            public virtual RepoItemInfo ActivityUniqueIDDisplayValueInfo
            {
                get
                {
                    return _activityuniqueiddisplayvalueInfo;
                }
            }

            /// <summary>
            /// The ActivityDetailsTab_Client_Text item.
            /// </summary>
            [RepositoryItem("0f619561-408d-4f9d-a21b-2266f0cdba01")]
            public virtual Ranorex.LegendTag ActivityDetailsTab_Client_Text
            {
                get
                {
                    return _activitydetailstab_client_textInfo.CreateAdapter<Ranorex.LegendTag>(true);
                }
            }

            /// <summary>
            /// The ActivityDetailsTab_Client_Text item info.
            /// </summary>
            [RepositoryItemInfo("0f619561-408d-4f9d-a21b-2266f0cdba01")]
            public virtual RepoItemInfo ActivityDetailsTab_Client_TextInfo
            {
                get
                {
                    return _activitydetailstab_client_textInfo;
                }
            }

            /// <summary>
            /// The UserSearch_Results_Edit_Btn_Row1 item.
            /// </summary>
            [RepositoryItem("112a63b6-0d37-4d93-8e1f-45faaf00ba82")]
            public virtual Ranorex.ButtonTag UserSearch_Results_Edit_Btn_Row1
            {
                get
                {
                    return _usersearch_results_edit_btn_row1Info.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The UserSearch_Results_Edit_Btn_Row1 item info.
            /// </summary>
            [RepositoryItemInfo("112a63b6-0d37-4d93-8e1f-45faaf00ba82")]
            public virtual RepoItemInfo UserSearch_Results_Edit_Btn_Row1Info
            {
                get
                {
                    return _usersearch_results_edit_btn_row1Info;
                }
            }

            /// <summary>
            /// The InternalUser_IsActive item.
            /// </summary>
            [RepositoryItem("b17a8a53-db8e-461a-813d-ede3bb00338f")]
            public virtual Ranorex.InputTag InternalUser_IsActive
            {
                get
                {
                    return _internaluser_isactiveInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InternalUser_IsActive item info.
            /// </summary>
            [RepositoryItemInfo("b17a8a53-db8e-461a-813d-ede3bb00338f")]
            public virtual RepoItemInfo InternalUser_IsActiveInfo
            {
                get
                {
                    return _internaluser_isactiveInfo;
                }
            }

            /// <summary>
            /// The InternalUser_Save_Btn item.
            /// </summary>
            [RepositoryItem("0d7d4dda-b1fc-45d1-bad1-ab4591dac13e")]
            public virtual Ranorex.InputTag InternalUser_Save_Btn
            {
                get
                {
                    return _internaluser_save_btnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InternalUser_Save_Btn item info.
            /// </summary>
            [RepositoryItemInfo("0d7d4dda-b1fc-45d1-bad1-ab4591dac13e")]
            public virtual RepoItemInfo InternalUser_Save_BtnInfo
            {
                get
                {
                    return _internaluser_save_btnInfo;
                }
            }

            /// <summary>
            /// The ExternalUser_Save_Btn item.
            /// </summary>
            [RepositoryItem("c3c70855-415a-4edb-a140-077e6c178218")]
            public virtual Ranorex.InputTag ExternalUser_Save_Btn
            {
                get
                {
                    return _externaluser_save_btnInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ExternalUser_Save_Btn item info.
            /// </summary>
            [RepositoryItemInfo("c3c70855-415a-4edb-a140-077e6c178218")]
            public virtual RepoItemInfo ExternalUser_Save_BtnInfo
            {
                get
                {
                    return _externaluser_save_btnInfo;
                }
            }

            /// <summary>
            /// The ConsultantPortalUser item.
            /// </summary>
            [RepositoryItem("8f27910d-c91a-407c-af82-8c3109a8378a")]
            public virtual Ranorex.InputTag ConsultantPortalUser
            {
                get
                {
                    return _consultantportaluserInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The ConsultantPortalUser item info.
            /// </summary>
            [RepositoryItemInfo("8f27910d-c91a-407c-af82-8c3109a8378a")]
            public virtual RepoItemInfo ConsultantPortalUserInfo
            {
                get
                {
                    return _consultantportaluserInfo;
                }
            }

            /// <summary>
            /// The LoginWasUnsuccessfulPleaseCorrectT item.
            /// </summary>
            [RepositoryItem("6b3ba1de-6afc-4a82-9072-e53ff3208f5b")]
            public virtual Ranorex.SpanTag LoginWasUnsuccessfulPleaseCorrectT
            {
                get
                {
                    return _loginwasunsuccessfulpleasecorrecttInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The LoginWasUnsuccessfulPleaseCorrectT item info.
            /// </summary>
            [RepositoryItemInfo("6b3ba1de-6afc-4a82-9072-e53ff3208f5b")]
            public virtual RepoItemInfo LoginWasUnsuccessfulPleaseCorrectTInfo
            {
                get
                {
                    return _loginwasunsuccessfulpleasecorrecttInfo;
                }
            }

            /// <summary>
            /// The CustomerPortalClass_Combined_Checkbox item.
            /// </summary>
            [RepositoryItem("747cdd3c-27f4-4c21-b13f-6f443270fdfb")]
            public virtual Ranorex.InputTag CustomerPortalClass_Combined_Checkbox
            {
                get
                {
                    return _customerportalclass_combined_checkboxInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The CustomerPortalClass_Combined_Checkbox item info.
            /// </summary>
            [RepositoryItemInfo("747cdd3c-27f4-4c21-b13f-6f443270fdfb")]
            public virtual RepoItemInfo CustomerPortalClass_Combined_CheckboxInfo
            {
                get
                {
                    return _customerportalclass_combined_checkboxInfo;
                }
            }
        }

        /// <summary>
        /// The CP3AppFolder folder.
        /// </summary>
        [RepositoryFolder("940286d5-7043-446c-ac46-a9ae1f08b968")]
        public partial class CP3AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _estimatedlossInfo;

            /// <summary>
            /// Creates a new CP3  folder.
            /// </summary>
            public CP3AppFolder(RepoGenBaseFolder parentFolder) :
                    base("CP3", "/dom[@domain~'cp3-usa-']", parentFolder, 2000, null, false, "940286d5-7043-446c-ac46-a9ae1f08b968", "")
            {
                _estimatedlossInfo = new RepoItemInfo(this, "EstimatedLoss", ".//div[#'RecommendationEditorWrapperComponent']//h5[@innertext='Estimated Loss']", "", 30000, null, "640383b5-eac2-421c-bf8a-073b322df5a9");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("940286d5-7043-446c-ac46-a9ae1f08b968")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("940286d5-7043-446c-ac46-a9ae1f08b968")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The EstimatedLoss item.
            /// </summary>
            [RepositoryItem("640383b5-eac2-421c-bf8a-073b322df5a9")]
            public virtual Ranorex.H5Tag EstimatedLoss
            {
                get
                {
                    return _estimatedlossInfo.CreateAdapter<Ranorex.H5Tag>(true);
                }
            }

            /// <summary>
            /// The EstimatedLoss item info.
            /// </summary>
            [RepositoryItemInfo("640383b5-eac2-421c-bf8a-073b322df5a9")]
            public virtual RepoItemInfo EstimatedLossInfo
            {
                get
                {
                    return _estimatedlossInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
