///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace BackOffice
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the _CP3Repository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("790a0019-a58d-4e89-837b-a4cad45a75b5")]
    public partial class _CP3Repository : RepoGenBaseFolder
    {
        static _CP3Repository instance = new _CP3Repository();
        _CP3RepositoryFolders.CP3AppFolder _cp3;
        _CP3RepositoryFolders.OpenAppFolder _open;

        /// <summary>
        /// Gets the singleton class instance representing the _CP3Repository element repository.
        /// </summary>
        [RepositoryFolder("790a0019-a58d-4e89-837b-a4cad45a75b5")]
        public static _CP3Repository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public _CP3Repository() 
            : base("_CP3Repository", "/", null, 0, false, "790a0019-a58d-4e89-837b-a4cad45a75b5", ".\\RepositoryImages\\_CP3Repository790a0019.rximgres")
        {
            _cp3 = new _CP3RepositoryFolders.CP3AppFolder(this);
            _open = new _CP3RepositoryFolders.OpenAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("790a0019-a58d-4e89-837b-a4cad45a75b5")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The CP3 folder.
        /// </summary>
        [RepositoryFolder("caa3c3ad-7fc6-453d-b4c8-aab07fd99cb5")]
        public virtual _CP3RepositoryFolders.CP3AppFolder CP3
        {
            get { return _cp3; }
        }

        /// <summary>
        /// The Open folder.
        /// </summary>
        [RepositoryFolder("984269d3-b34a-4ce4-9325-cf7a1de97550")]
        public virtual _CP3RepositoryFolders.OpenAppFolder Open
        {
            get { return _open; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class _CP3RepositoryFolders
    {
        /// <summary>
        /// The CP3AppFolder folder.
        /// </summary>
        [RepositoryFolder("caa3c3ad-7fc6-453d-b4c8-aab07fd99cb5")]
        public partial class CP3AppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _inputemailInfo;
            RepoItemInfo _inputpasswordInfo;
            RepoItemInfo _loginbuttonInfo;
            RepoItemInfo _firstslideInfo;
            RepoItemInfo _loadingInfo;
            RepoItemInfo _navbar_activitiesInfo;
            RepoItemInfo _myactivities_listitemInfo;
            RepoItemInfo _manageactivities_listitemInfo;
            RepoItemInfo _activities_viewdetails_btn_row1Info;
            RepoItemInfo _activities_viewsurvey_btn_row1Info;
            RepoItemInfo _survey_add_btnInfo;
            RepoItemInfo _survey_attachments_btnInfo;
            RepoItemInfo _survey_add_riInfo;
            RepoItemInfo _ri_priority_selectInfo;
            RepoItemInfo _ri_priority_highInfo;
            RepoItemInfo _ri_priority_normalInfo;
            RepoItemInfo _ri_status_selectInfo;
            RepoItemInfo _ri_status_newInfo;
            RepoItemInfo _ri_expenditure_select_7Info;
            RepoItemInfo _ri_expenditure_select_8Info;
            RepoItemInfo _ri_expenditure_capitalexpenditureInfo;
            RepoItemInfo _estimatedlossInfo;
            RepoItemInfo _ri_status_closedInfo;
            RepoItemInfo _ri_done_btnInfo;
            RepoItemInfo _survey_riview_btnInfo;
            RepoItemInfo _riview_priorityhigh_badgeInfo;
            RepoItemInfo _riview_prioritynormal_badgeInfo;
            RepoItemInfo _riview_statusnew_badgeInfo;
            RepoItemInfo _riview_statusclosed_badgeInfo;
            RepoItemInfo _riview_close_btnInfo;
            RepoItemInfo _riview_edit_btnInfo;
            RepoItemInfo _survey_question1_textinputInfo;
            RepoItemInfo _survey_question1_yesInfo;
            RepoItemInfo _survey_question1_yes_tickInfo;
            RepoItemInfo _survey_section_executivesummaryInfo;
            RepoItemInfo _survey_next_btnInfo;
            RepoItemInfo _survey_previous_btnInfo;
            RepoItemInfo _questiononeanswertextInfo;
            RepoItemInfo _questionaddphotoInfo;
            RepoItemInfo _addattachments_dropfilesheretoupload_textInfo;
            RepoItemInfo _survey_print_btnInfo;
            RepoItemInfo _export_modal_headertextInfo;
            RepoItemInfo _export_modal_downloadpdf_btnInfo;
            RepoItemInfo _navbar_signedinuserInfo;
            RepoItemInfo _signoutInfo;
            RepoItemInfo _survey_submit_btnInfo;
            RepoItemInfo _yesInfo;
            RepoItemInfo _confirmation_modal_headertextInfo;
            RepoItemInfo _areyousureyouwanttosubmitInfo;
            RepoItemInfo _reportsubmitted_modal_headertextInfo;
            RepoItemInfo _reportsubmitted_modal_viewdetails_btnInfo;
            RepoItemInfo _activity_internalstatusInfo;
            RepoItemInfo _activity_searchInfo;

            /// <summary>
            /// Creates a new CP3  folder.
            /// </summary>
            public CP3AppFolder(RepoGenBaseFolder parentFolder) :
                    base("CP3", "/dom[@domain~'cp3-usa-']", parentFolder, 2000, null, false, "caa3c3ad-7fc6-453d-b4c8-aab07fd99cb5", "")
            {
                _inputemailInfo = new RepoItemInfo(this, "InputEmail", ".//input[#'inputEmail']", ".//input[#'inputEmail']", 30000, null, "cd36dd33-f0af-4449-8ebb-521bfebc4613");
                _inputpasswordInfo = new RepoItemInfo(this, "InputPassword", ".//input[#'inputPassword']", ".//input[#'inputPassword']", 30000, null, "fefad905-fd20-4b1a-a511-f294dc6932df");
                _loginbuttonInfo = new RepoItemInfo(this, "LoginButton", ".//button[#'login-button']", ".//button[#'login-button']", 30000, null, "424351f7-3c54-4032-b58a-66b82bd578ca");
                _firstslideInfo = new RepoItemInfo(this, "FirstSlide", ".//div[#'home-carousel']//img[@alt='First slide']", ".//div[#'home-carousel']//img[@alt='First slide']", 30000, null, "b28890b3-3fec-48c7-86df-2cf5483b4283");
                _loadingInfo = new RepoItemInfo(this, "Loading", ".//div[#'loading']", ".//div[#'loading']", 30000, null, "fd3a384a-5ea9-4c22-9fa7-fc3d039fdcc6");
                _navbar_activitiesInfo = new RepoItemInfo(this, "Navbar_Activities", ".//div[#'navbarSupportedContent']//span[@innertext~'Activities']", ".//div[#'navbarSupportedContent']//span[@innertext>'                        Activities']", 30000, null, "b7c6e47d-4766-48f6-a484-2a37054d8b1e");
                _myactivities_listitemInfo = new RepoItemInfo(this, "MyActivities_ListItem", ".//div[#'navbarSupportedContent']/ul[1]/li[5]/span/a[@innertext~'My Activities']", "", 30000, null, "d6c19f12-a5c8-4138-8647-17a72d966e5d");
                _manageactivities_listitemInfo = new RepoItemInfo(this, "ManageActivities_ListItem", ".//div[#'navbarSupportedContent']/ul[1]/li/?/span/a[@innertext~'Manage Activities']", "", 30000, null, "b912f7ff-76d5-43f5-ba48-897d82849470");
                _activities_viewdetails_btn_row1Info = new RepoItemInfo(this, "Activities_ViewDetails_Btn_Row1", ".//div[#'my-activities-container']//a[@innertext='View Details']", ".//div[#'my-activities-container']//a[@innertext='View Details']", 30000, null, "51400da9-871a-459c-9132-8eea7514792f");
                _activities_viewsurvey_btn_row1Info = new RepoItemInfo(this, "Activities_ViewSurvey_Btn_Row1", ".//div[#'my-activities-container']//a[@innertext='View Survey']", ".//div[#'my-activities-container']//a[@innertext='View Details']", 30000, null, "9b192db1-4dcf-403d-a9c6-6b826d047aeb");
                _survey_add_btnInfo = new RepoItemInfo(this, "Survey_Add_Btn", ".//div[#'questionnaire-section']/div/div[2]/div/div[2]/div[2]/div", ".//div[#'questionnaire-section']/div/div[2]/div/div[2]/div[2]/div/button[@title='']", 30000, null, "f75dedb0-cc8d-4cec-bba0-156b042d93a3");
                _survey_attachments_btnInfo = new RepoItemInfo(this, "Survey_Attachments_Btn", ".//div[#'questionnaire-section']//span[@innertext='1']", ".//div[#'questionnaire-section']//span[@innertext='1']", 30000, null, "0f333eed-b17c-4b85-aef4-7070f145adc3");
                _survey_add_riInfo = new RepoItemInfo(this, "Survey_Add_RI", ".//div[#'question-add-ri']", ".//div[#'question-add-ri']", 30000, null, "4b7e7df0-8c3e-4c31-8d9e-58d22e405ad3");
                _ri_priority_selectInfo = new RepoItemInfo(this, "RI_Priority_Select", ".//div[#'ri-details-modal']//form/div/div[2]/div[1]/div/div[3]/div/div", ".//div[#'ri-details-modal']//form/div/div[2]/div[1]/div/div[3]/div/div", 30000, null, "50718d53-da0b-4b57-9b13-13c883a95ba9");
                _ri_priority_highInfo = new RepoItemInfo(this, "RI_Priority_High", ".//div[#'ri-details-modal']//span[@innertext='High']", ".//div[#'ri-details-modal']//span[@innertext='High']", 30000, null, "5ddd7b3d-96f9-4d71-8a66-f4fd360bcbea");
                _ri_priority_normalInfo = new RepoItemInfo(this, "RI_Priority_Normal", ".//div[#'ri-details-modal']//span[@innertext='Normal']", ".//div[#'ri-details-modal']//span[@innertext='High']", 30000, null, "fd0e5f60-abbf-409a-aee8-e56b13d6a62a");
                _ri_status_selectInfo = new RepoItemInfo(this, "RI_Status_Select", ".//div[#'ri-details-modal']//form/div/div[2]/div[1]/div/div[6]/div/div", ".//div[#'ri-details-modal']//form/div/div[2]/div[1]/div/div[6]/div/div", 30000, null, "d99c3434-d9ce-4ce1-9f70-fc0d90566ab4");
                _ri_status_newInfo = new RepoItemInfo(this, "RI_Status_New", ".//div[#'ri-details-modal']//span[@innertext='New']", ".//div[#'ri-details-modal']//span[@innertext='High']", 30000, null, "f84653ac-792a-415b-b02f-cfe28fc44097");
                _ri_expenditure_select_7Info = new RepoItemInfo(this, "RI_Expenditure_Select_7", ".//div[#'ri-details-modal']//form/div/div[2]/div[1]/div/div[7]/div/div", "", 1000, null, "16523fe2-8d24-4382-bdb2-9efd6dc1e7a7");
                _ri_expenditure_select_8Info = new RepoItemInfo(this, "RI_Expenditure_Select_8", ".//div[#'ri-details-modal']//form/div/div[2]/div[1]/div/div[8]/div/div", "", 1000, null, "90b1cc3e-6ff4-4085-b7c0-1a4411b7cc9b");
                _ri_expenditure_capitalexpenditureInfo = new RepoItemInfo(this, "RI_Expenditure_CapitalExpenditure", ".//div[#'ri-details-modal']//span[@innertext='Capital Expenditure']", ".//div[#'ri-details-modal']//span[@innertext='High']", 30000, null, "1f876206-6c3f-4def-9568-ab31a6b755e5");
                _estimatedlossInfo = new RepoItemInfo(this, "EstimatedLoss", ".//div[#'RecommendationEditorWrapperComponent']//h5[@innertext='Estimated Loss']", "", 30000, null, "9b914d22-d207-41ce-97a8-58d4979c843f");
                _ri_status_closedInfo = new RepoItemInfo(this, "RI_Status_Closed", ".//div[#'ri-details-modal']//span[@innertext='Closed']", ".//div[#'ri-details-modal']//span[@innertext='High']", 30000, null, "8633d79f-32f1-40b0-a9e4-fc3b9dd60a0a");
                _ri_done_btnInfo = new RepoItemInfo(this, "RI_Done_Btn", ".//div[#'ri-details-modal']//button[@innertext='Done']", ".//div[#'ri-details-modal']//button[@innertext='Done']", 30000, null, "44123817-a6ce-4acc-ba15-6c41f077b531");
                _survey_riview_btnInfo = new RepoItemInfo(this, "Survey_RIView_Btn", ".//div[#'questionnaire-section']/div/div[2]/div/div[2]/div[2]/button[2]", ".//div[#'questionnaire-section']/div/div[2]/div/div[2]/div[2]/button[2]", 30000, null, "78c1a5c0-2c49-4f78-a5f9-dd06385eb9a0");
                _riview_priorityhigh_badgeInfo = new RepoItemInfo(this, "RIView_PriorityHigh_Badge", ".//div[#'question-ris-modal']//span[@innertext='Priority : High']", ".//div[#'question-ris-modal']//span[@innertext='Priority : High']", 30000, null, "00902278-9c73-4b48-bc9d-03fda28d0287");
                _riview_prioritynormal_badgeInfo = new RepoItemInfo(this, "RIView_PriorityNormal_Badge", ".//div[#'question-ris-modal']//span[@innertext='Priority : Normal']", ".//div[#'question-ris-modal']//span[@innertext='Priority : High']", 30000, null, "d5521185-9e4f-48b0-a465-743e0ac1a789");
                _riview_statusnew_badgeInfo = new RepoItemInfo(this, "RIView_StatusNew_Badge", ".//div[#'question-ris-modal']//span[@innertext='Status : New']", ".//div[#'question-ris-modal']//span[@innertext='Status : New']", 30000, null, "70f60862-3a94-446b-8d7b-ec7137b3d8c2");
                _riview_statusclosed_badgeInfo = new RepoItemInfo(this, "RIView_StatusClosed_Badge", ".//div[#'question-ris-modal']//span[@innertext='Status : Closed']", ".//div[#'question-ris-modal']//span[@innertext='Status : New']", 30000, null, "f5ba786b-515e-45ce-983e-13f0acf2602e");
                _riview_close_btnInfo = new RepoItemInfo(this, "RIView_Close_Btn", ".//div[#'question-ris-modal']//button[@innertext~'Close ']", ".//div[#'question-ris-modal']//button[@innertext=' Close ']", 30000, null, "8ffe5cec-f581-41b9-ae0d-6c8317d3ac0e");
                _riview_edit_btnInfo = new RepoItemInfo(this, "RIView_Edit_Btn", ".//div[#'question-ris-modal']//button[@innertext=' Edit']", ".//div[#'question-ris-modal']//button[@innertext=' Edit']", 30000, null, "fed90404-4bfb-4b0c-81fd-6b0aee3832e0");
                _survey_question1_textinputInfo = new RepoItemInfo(this, "Survey_Question1_TextInput", ".//div[#'section-container']//iframe//body[#'tinymce']", ".//div[#'section-container']//iframe//body[#'tinymce']", 30000, null, "c2e8bccf-a1b0-482e-911f-aa9f7213bc41");
                _survey_question1_yesInfo = new RepoItemInfo(this, "Survey_Question1_Yes", ".//div[#'section-container']//div[@innertext~'Yes ']", ".//div[#'section-container']//div[@innertext='            Yes ']", 30000, null, "4502579e-a5cf-4155-a858-cbe383a6349c");
                _survey_question1_yes_tickInfo = new RepoItemInfo(this, "Survey_Question1_Yes_Tick", ".//div[#'section-container']//div[@innertext~'Yes ']/i", ".//div[#'section-container']//div[@innertext='            Yes ']/i", 30000, null, "59ab7194-b16d-432e-a6ae-fc7a86824abf");
                _survey_section_executivesummaryInfo = new RepoItemInfo(this, "Survey_Section_ExecutiveSummary", ".//div[#'question-list']//span[@innertext~'Executive Summary']", ".//div[#'question-list']//span[@innertext='Executive Summary']", 30000, null, "84246a39-7014-485e-9a7a-d0c1faeb711b");
                _survey_next_btnInfo = new RepoItemInfo(this, "Survey_Next_Btn", ".//button[#'q-nav-next']", ".//button[#'q-nav-next']", 30000, null, "31b0d766-dc60-45d6-b004-31e7da5b2d4a");
                _survey_previous_btnInfo = new RepoItemInfo(this, "Survey_Previous_Btn", ".//button[#'q-nav-prev']", ".//a[#'q-nav-prev']", 30000, null, "f3849c5e-d3b8-4c28-8e10-0d9cf810dbfc");
                _questiononeanswertextInfo = new RepoItemInfo(this, "QuestionOneAnswerText", ".//div[#'section-container']//iframe//body[#'tinymce']/p[@innertext='Question One Answer Text']", ".//div[#'section-container']//iframe//body[#'tinymce']/p[@innertext='Question One Answer Text']", 30000, null, "67c6dc48-e472-4c95-bf5a-91b9f5ac8982");
                _questionaddphotoInfo = new RepoItemInfo(this, "QuestionAddPhoto", ".//div[#'question-add-photo']", ".//div[#'question-add-photo']", 30000, null, "17952ccf-47b6-484d-8247-c10c20ed1a40");
                _addattachments_dropfilesheretoupload_textInfo = new RepoItemInfo(this, "AddAttachments_DropFilesHereToUpload_Text", ".//form[#'attachment-dropzone']/?/?/button[@innertext='Drop files here to upload']", ".//form[#'attachment-dropzone']/?/?/button[@innertext='Drop files here to upload']", 30000, null, "d86c6774-87b7-4ae5-bda7-82d05a281ed3");
                _survey_print_btnInfo = new RepoItemInfo(this, "Survey_Print_Btn", ".//div[#'page-content-wrapper']//span[@innertext='Print']", ".//div[#'page-content-wrapper']//span[@innertext='Print']", 30000, null, "4fd1aed3-b494-42f5-acb6-fa97c02bcbbc");
                _export_modal_headertextInfo = new RepoItemInfo(this, "Export_Modal_HeaderText", ".//div[#'downloadReportsModal']//h5[@innertext='Export']", ".//div[#'downloadReportsModal']//h5[@innertext='Export']", 30000, null, "36ef6eeb-98c4-4602-b1bc-f38f37ec0891");
                _export_modal_downloadpdf_btnInfo = new RepoItemInfo(this, "Export_Modal_DownloadPDF_Btn", ".//div[#'downloadReportsModal']//a[@innertext~'Download']", ".//div[#'downloadReportsModal']//a[@innertext>'                    Download']", 30000, null, "c14a6f2c-954f-4e99-aee9-62411a137634");
                _navbar_signedinuserInfo = new RepoItemInfo(this, "Navbar_SignedInUser", ".//div[#'navbarSupportedContent']/ul[2]/li[3]", ".//div[#'navbarSupportedContent']/ul[2]/li[3]", 30000, null, "36dbab1f-5de6-4f08-b959-de47d427e321");
                _signoutInfo = new RepoItemInfo(this, "SignOut", ".//div[#'navbarSupportedContent']//a[@innertext=' Sign Out']", ".//div[#'navbarSupportedContent']//a[@innertext=' Sign Out']", 30000, null, "79fbad80-48aa-454c-8e91-3c7b24be5cfd");
                _survey_submit_btnInfo = new RepoItemInfo(this, "Survey_Submit_Btn", ".//div[#'page-content-wrapper']//span[@innertext='Submit']", ".//div[#'page-content-wrapper']//span[@innertext='Submit']", 30000, null, "5a4317f4-cf50-4902-9170-7a3ba11e86d2");
                _yesInfo = new RepoItemInfo(this, "Yes", ".//button[@innertext='Yes ']", ".//div[#'confirm-modal']//button[@innertext='Yes ']", 30000, null, "f1606ed2-32dd-48e0-8457-7be0d2beedcf");
                _confirmation_modal_headertextInfo = new RepoItemInfo(this, "Confirmation_Modal_HeaderText", ".//h5[@innertext~'Confirmation']", ".//div[#'confirm-modal']//h5[@innertext=' Confirmation']", 30000, null, "282180d7-ce0d-45cf-8ec7-ec2f06bd5618");
                _areyousureyouwanttosubmitInfo = new RepoItemInfo(this, "AreYouSureYouWantToSubmit", ".//p[@innertext>'Are you sure you want to']", ".//div[#'confirm-modal']//p[@innertext>'Are you sure you want to']", 30000, null, "093753d7-d09d-41ba-a55d-941dc0ecc220");
                _reportsubmitted_modal_headertextInfo = new RepoItemInfo(this, "ReportSubmitted_Modal_HeaderText", ".//div[#'post-submit-modal']//h5[@innertext=' Report Submitted']", ".//div[#'post-submit-modal']//h5[@innertext=' Report Submitted']", 30000, null, "2ca9d6c3-d076-404d-8e1b-739d90dd57cd");
                _reportsubmitted_modal_viewdetails_btnInfo = new RepoItemInfo(this, "ReportSubmitted_Modal_ViewDetails_Btn", ".//button[#'activity-submit-details-button']", ".//button[#'activity-submit-details-button']", 30000, null, "55d08da7-2a21-4f8b-bb47-d5bdff6f2714");
                _activity_internalstatusInfo = new RepoItemInfo(this, "Activity_InternalStatus", ".//div[#'nav-details']//span[@title='']", ".//div[#'nav-details']//span[@title='']", 30000, null, "32d4bf33-8746-4e21-a5a6-72d05c316ce9");
                _activity_searchInfo = new RepoItemInfo(this, "Activity_Search", ".//div[#'page-content-wrapper']//input[@type='text']", ".//div[#'page-content-wrapper']//input[@type='text']", 30000, null, "1d377535-72b6-475d-b0b4-6686680b2f33");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("caa3c3ad-7fc6-453d-b4c8-aab07fd99cb5")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("caa3c3ad-7fc6-453d-b4c8-aab07fd99cb5")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The InputEmail item.
            /// </summary>
            [RepositoryItem("cd36dd33-f0af-4449-8ebb-521bfebc4613")]
            public virtual Ranorex.InputTag InputEmail
            {
                get
                {
                    return _inputemailInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputEmail item info.
            /// </summary>
            [RepositoryItemInfo("cd36dd33-f0af-4449-8ebb-521bfebc4613")]
            public virtual RepoItemInfo InputEmailInfo
            {
                get
                {
                    return _inputemailInfo;
                }
            }

            /// <summary>
            /// The InputPassword item.
            /// </summary>
            [RepositoryItem("fefad905-fd20-4b1a-a511-f294dc6932df")]
            public virtual Ranorex.InputTag InputPassword
            {
                get
                {
                    return _inputpasswordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The InputPassword item info.
            /// </summary>
            [RepositoryItemInfo("fefad905-fd20-4b1a-a511-f294dc6932df")]
            public virtual RepoItemInfo InputPasswordInfo
            {
                get
                {
                    return _inputpasswordInfo;
                }
            }

            /// <summary>
            /// The LoginButton item.
            /// </summary>
            [RepositoryItem("424351f7-3c54-4032-b58a-66b82bd578ca")]
            public virtual Ranorex.ButtonTag LoginButton
            {
                get
                {
                    return _loginbuttonInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The LoginButton item info.
            /// </summary>
            [RepositoryItemInfo("424351f7-3c54-4032-b58a-66b82bd578ca")]
            public virtual RepoItemInfo LoginButtonInfo
            {
                get
                {
                    return _loginbuttonInfo;
                }
            }

            /// <summary>
            /// The FirstSlide item.
            /// </summary>
            [RepositoryItem("b28890b3-3fec-48c7-86df-2cf5483b4283")]
            public virtual Ranorex.ImgTag FirstSlide
            {
                get
                {
                    return _firstslideInfo.CreateAdapter<Ranorex.ImgTag>(true);
                }
            }

            /// <summary>
            /// The FirstSlide item info.
            /// </summary>
            [RepositoryItemInfo("b28890b3-3fec-48c7-86df-2cf5483b4283")]
            public virtual RepoItemInfo FirstSlideInfo
            {
                get
                {
                    return _firstslideInfo;
                }
            }

            /// <summary>
            /// The Loading item.
            /// </summary>
            [RepositoryItem("fd3a384a-5ea9-4c22-9fa7-fc3d039fdcc6")]
            public virtual Ranorex.DivTag Loading
            {
                get
                {
                    return _loadingInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Loading item info.
            /// </summary>
            [RepositoryItemInfo("fd3a384a-5ea9-4c22-9fa7-fc3d039fdcc6")]
            public virtual RepoItemInfo LoadingInfo
            {
                get
                {
                    return _loadingInfo;
                }
            }

            /// <summary>
            /// The Navbar_Activities item.
            /// </summary>
            [RepositoryItem("b7c6e47d-4766-48f6-a484-2a37054d8b1e")]
            public virtual Ranorex.SpanTag Navbar_Activities
            {
                get
                {
                    return _navbar_activitiesInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Navbar_Activities item info.
            /// </summary>
            [RepositoryItemInfo("b7c6e47d-4766-48f6-a484-2a37054d8b1e")]
            public virtual RepoItemInfo Navbar_ActivitiesInfo
            {
                get
                {
                    return _navbar_activitiesInfo;
                }
            }

            /// <summary>
            /// The MyActivities_ListItem item.
            /// </summary>
            [RepositoryItem("d6c19f12-a5c8-4138-8647-17a72d966e5d")]
            public virtual Ranorex.ATag MyActivities_ListItem
            {
                get
                {
                    return _myactivities_listitemInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The MyActivities_ListItem item info.
            /// </summary>
            [RepositoryItemInfo("d6c19f12-a5c8-4138-8647-17a72d966e5d")]
            public virtual RepoItemInfo MyActivities_ListItemInfo
            {
                get
                {
                    return _myactivities_listitemInfo;
                }
            }

            /// <summary>
            /// The ManageActivities_ListItem item.
            /// </summary>
            [RepositoryItem("b912f7ff-76d5-43f5-ba48-897d82849470")]
            public virtual Ranorex.ATag ManageActivities_ListItem
            {
                get
                {
                    return _manageactivities_listitemInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The ManageActivities_ListItem item info.
            /// </summary>
            [RepositoryItemInfo("b912f7ff-76d5-43f5-ba48-897d82849470")]
            public virtual RepoItemInfo ManageActivities_ListItemInfo
            {
                get
                {
                    return _manageactivities_listitemInfo;
                }
            }

            /// <summary>
            /// The Activities_ViewDetails_Btn_Row1 item.
            /// </summary>
            [RepositoryItem("51400da9-871a-459c-9132-8eea7514792f")]
            public virtual Ranorex.ATag Activities_ViewDetails_Btn_Row1
            {
                get
                {
                    return _activities_viewdetails_btn_row1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Activities_ViewDetails_Btn_Row1 item info.
            /// </summary>
            [RepositoryItemInfo("51400da9-871a-459c-9132-8eea7514792f")]
            public virtual RepoItemInfo Activities_ViewDetails_Btn_Row1Info
            {
                get
                {
                    return _activities_viewdetails_btn_row1Info;
                }
            }

            /// <summary>
            /// The Activities_ViewSurvey_Btn_Row1 item.
            /// </summary>
            [RepositoryItem("9b192db1-4dcf-403d-a9c6-6b826d047aeb")]
            public virtual Ranorex.ATag Activities_ViewSurvey_Btn_Row1
            {
                get
                {
                    return _activities_viewsurvey_btn_row1Info.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Activities_ViewSurvey_Btn_Row1 item info.
            /// </summary>
            [RepositoryItemInfo("9b192db1-4dcf-403d-a9c6-6b826d047aeb")]
            public virtual RepoItemInfo Activities_ViewSurvey_Btn_Row1Info
            {
                get
                {
                    return _activities_viewsurvey_btn_row1Info;
                }
            }

            /// <summary>
            /// The Survey_Add_Btn item.
            /// </summary>
            [RepositoryItem("f75dedb0-cc8d-4cec-bba0-156b042d93a3")]
            public virtual Ranorex.DivTag Survey_Add_Btn
            {
                get
                {
                    return _survey_add_btnInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Survey_Add_Btn item info.
            /// </summary>
            [RepositoryItemInfo("f75dedb0-cc8d-4cec-bba0-156b042d93a3")]
            public virtual RepoItemInfo Survey_Add_BtnInfo
            {
                get
                {
                    return _survey_add_btnInfo;
                }
            }

            /// <summary>
            /// The Survey_Attachments_Btn item.
            /// </summary>
            [RepositoryItem("0f333eed-b17c-4b85-aef4-7070f145adc3")]
            public virtual Ranorex.SpanTag Survey_Attachments_Btn
            {
                get
                {
                    return _survey_attachments_btnInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Survey_Attachments_Btn item info.
            /// </summary>
            [RepositoryItemInfo("0f333eed-b17c-4b85-aef4-7070f145adc3")]
            public virtual RepoItemInfo Survey_Attachments_BtnInfo
            {
                get
                {
                    return _survey_attachments_btnInfo;
                }
            }

            /// <summary>
            /// The Survey_Add_RI item.
            /// </summary>
            [RepositoryItem("4b7e7df0-8c3e-4c31-8d9e-58d22e405ad3")]
            public virtual Ranorex.DivTag Survey_Add_RI
            {
                get
                {
                    return _survey_add_riInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Survey_Add_RI item info.
            /// </summary>
            [RepositoryItemInfo("4b7e7df0-8c3e-4c31-8d9e-58d22e405ad3")]
            public virtual RepoItemInfo Survey_Add_RIInfo
            {
                get
                {
                    return _survey_add_riInfo;
                }
            }

            /// <summary>
            /// The RI_Priority_Select item.
            /// </summary>
            [RepositoryItem("50718d53-da0b-4b57-9b13-13c883a95ba9")]
            public virtual Ranorex.DivTag RI_Priority_Select
            {
                get
                {
                    return _ri_priority_selectInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The RI_Priority_Select item info.
            /// </summary>
            [RepositoryItemInfo("50718d53-da0b-4b57-9b13-13c883a95ba9")]
            public virtual RepoItemInfo RI_Priority_SelectInfo
            {
                get
                {
                    return _ri_priority_selectInfo;
                }
            }

            /// <summary>
            /// The RI_Priority_High item.
            /// </summary>
            [RepositoryItem("5ddd7b3d-96f9-4d71-8a66-f4fd360bcbea")]
            public virtual Ranorex.SpanTag RI_Priority_High
            {
                get
                {
                    return _ri_priority_highInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The RI_Priority_High item info.
            /// </summary>
            [RepositoryItemInfo("5ddd7b3d-96f9-4d71-8a66-f4fd360bcbea")]
            public virtual RepoItemInfo RI_Priority_HighInfo
            {
                get
                {
                    return _ri_priority_highInfo;
                }
            }

            /// <summary>
            /// The RI_Priority_Normal item.
            /// </summary>
            [RepositoryItem("fd0e5f60-abbf-409a-aee8-e56b13d6a62a")]
            public virtual Ranorex.SpanTag RI_Priority_Normal
            {
                get
                {
                    return _ri_priority_normalInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The RI_Priority_Normal item info.
            /// </summary>
            [RepositoryItemInfo("fd0e5f60-abbf-409a-aee8-e56b13d6a62a")]
            public virtual RepoItemInfo RI_Priority_NormalInfo
            {
                get
                {
                    return _ri_priority_normalInfo;
                }
            }

            /// <summary>
            /// The RI_Status_Select item.
            /// </summary>
            [RepositoryItem("d99c3434-d9ce-4ce1-9f70-fc0d90566ab4")]
            public virtual Ranorex.DivTag RI_Status_Select
            {
                get
                {
                    return _ri_status_selectInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The RI_Status_Select item info.
            /// </summary>
            [RepositoryItemInfo("d99c3434-d9ce-4ce1-9f70-fc0d90566ab4")]
            public virtual RepoItemInfo RI_Status_SelectInfo
            {
                get
                {
                    return _ri_status_selectInfo;
                }
            }

            /// <summary>
            /// The RI_Status_New item.
            /// </summary>
            [RepositoryItem("f84653ac-792a-415b-b02f-cfe28fc44097")]
            public virtual Ranorex.SpanTag RI_Status_New
            {
                get
                {
                    return _ri_status_newInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The RI_Status_New item info.
            /// </summary>
            [RepositoryItemInfo("f84653ac-792a-415b-b02f-cfe28fc44097")]
            public virtual RepoItemInfo RI_Status_NewInfo
            {
                get
                {
                    return _ri_status_newInfo;
                }
            }

            /// <summary>
            /// The RI_Expenditure_Select_7 item.
            /// </summary>
            [RepositoryItem("16523fe2-8d24-4382-bdb2-9efd6dc1e7a7")]
            public virtual Ranorex.DivTag RI_Expenditure_Select_7
            {
                get
                {
                    return _ri_expenditure_select_7Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The RI_Expenditure_Select_7 item info.
            /// </summary>
            [RepositoryItemInfo("16523fe2-8d24-4382-bdb2-9efd6dc1e7a7")]
            public virtual RepoItemInfo RI_Expenditure_Select_7Info
            {
                get
                {
                    return _ri_expenditure_select_7Info;
                }
            }

            /// <summary>
            /// The RI_Expenditure_Select_8 item.
            /// </summary>
            [RepositoryItem("90b1cc3e-6ff4-4085-b7c0-1a4411b7cc9b")]
            public virtual Ranorex.DivTag RI_Expenditure_Select_8
            {
                get
                {
                    return _ri_expenditure_select_8Info.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The RI_Expenditure_Select_8 item info.
            /// </summary>
            [RepositoryItemInfo("90b1cc3e-6ff4-4085-b7c0-1a4411b7cc9b")]
            public virtual RepoItemInfo RI_Expenditure_Select_8Info
            {
                get
                {
                    return _ri_expenditure_select_8Info;
                }
            }

            /// <summary>
            /// The RI_Expenditure_CapitalExpenditure item.
            /// </summary>
            [RepositoryItem("1f876206-6c3f-4def-9568-ab31a6b755e5")]
            public virtual Ranorex.SpanTag RI_Expenditure_CapitalExpenditure
            {
                get
                {
                    return _ri_expenditure_capitalexpenditureInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The RI_Expenditure_CapitalExpenditure item info.
            /// </summary>
            [RepositoryItemInfo("1f876206-6c3f-4def-9568-ab31a6b755e5")]
            public virtual RepoItemInfo RI_Expenditure_CapitalExpenditureInfo
            {
                get
                {
                    return _ri_expenditure_capitalexpenditureInfo;
                }
            }

            /// <summary>
            /// The EstimatedLoss item.
            /// </summary>
            [RepositoryItem("9b914d22-d207-41ce-97a8-58d4979c843f")]
            public virtual Ranorex.H5Tag EstimatedLoss
            {
                get
                {
                    return _estimatedlossInfo.CreateAdapter<Ranorex.H5Tag>(true);
                }
            }

            /// <summary>
            /// The EstimatedLoss item info.
            /// </summary>
            [RepositoryItemInfo("9b914d22-d207-41ce-97a8-58d4979c843f")]
            public virtual RepoItemInfo EstimatedLossInfo
            {
                get
                {
                    return _estimatedlossInfo;
                }
            }

            /// <summary>
            /// The RI_Status_Closed item.
            /// </summary>
            [RepositoryItem("8633d79f-32f1-40b0-a9e4-fc3b9dd60a0a")]
            public virtual Ranorex.SpanTag RI_Status_Closed
            {
                get
                {
                    return _ri_status_closedInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The RI_Status_Closed item info.
            /// </summary>
            [RepositoryItemInfo("8633d79f-32f1-40b0-a9e4-fc3b9dd60a0a")]
            public virtual RepoItemInfo RI_Status_ClosedInfo
            {
                get
                {
                    return _ri_status_closedInfo;
                }
            }

            /// <summary>
            /// The RI_Done_Btn item.
            /// </summary>
            [RepositoryItem("44123817-a6ce-4acc-ba15-6c41f077b531")]
            public virtual Ranorex.ButtonTag RI_Done_Btn
            {
                get
                {
                    return _ri_done_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The RI_Done_Btn item info.
            /// </summary>
            [RepositoryItemInfo("44123817-a6ce-4acc-ba15-6c41f077b531")]
            public virtual RepoItemInfo RI_Done_BtnInfo
            {
                get
                {
                    return _ri_done_btnInfo;
                }
            }

            /// <summary>
            /// The Survey_RIView_Btn item.
            /// </summary>
            [RepositoryItem("78c1a5c0-2c49-4f78-a5f9-dd06385eb9a0")]
            public virtual Ranorex.Button Survey_RIView_Btn
            {
                get
                {
                    return _survey_riview_btnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Survey_RIView_Btn item info.
            /// </summary>
            [RepositoryItemInfo("78c1a5c0-2c49-4f78-a5f9-dd06385eb9a0")]
            public virtual RepoItemInfo Survey_RIView_BtnInfo
            {
                get
                {
                    return _survey_riview_btnInfo;
                }
            }

            /// <summary>
            /// The RIView_PriorityHigh_Badge item.
            /// </summary>
            [RepositoryItem("00902278-9c73-4b48-bc9d-03fda28d0287")]
            public virtual Ranorex.SpanTag RIView_PriorityHigh_Badge
            {
                get
                {
                    return _riview_priorityhigh_badgeInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The RIView_PriorityHigh_Badge item info.
            /// </summary>
            [RepositoryItemInfo("00902278-9c73-4b48-bc9d-03fda28d0287")]
            public virtual RepoItemInfo RIView_PriorityHigh_BadgeInfo
            {
                get
                {
                    return _riview_priorityhigh_badgeInfo;
                }
            }

            /// <summary>
            /// The RIView_PriorityNormal_Badge item.
            /// </summary>
            [RepositoryItem("d5521185-9e4f-48b0-a465-743e0ac1a789")]
            public virtual Ranorex.SpanTag RIView_PriorityNormal_Badge
            {
                get
                {
                    return _riview_prioritynormal_badgeInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The RIView_PriorityNormal_Badge item info.
            /// </summary>
            [RepositoryItemInfo("d5521185-9e4f-48b0-a465-743e0ac1a789")]
            public virtual RepoItemInfo RIView_PriorityNormal_BadgeInfo
            {
                get
                {
                    return _riview_prioritynormal_badgeInfo;
                }
            }

            /// <summary>
            /// The RIView_StatusNew_Badge item.
            /// </summary>
            [RepositoryItem("70f60862-3a94-446b-8d7b-ec7137b3d8c2")]
            public virtual Ranorex.SpanTag RIView_StatusNew_Badge
            {
                get
                {
                    return _riview_statusnew_badgeInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The RIView_StatusNew_Badge item info.
            /// </summary>
            [RepositoryItemInfo("70f60862-3a94-446b-8d7b-ec7137b3d8c2")]
            public virtual RepoItemInfo RIView_StatusNew_BadgeInfo
            {
                get
                {
                    return _riview_statusnew_badgeInfo;
                }
            }

            /// <summary>
            /// The RIView_StatusClosed_Badge item.
            /// </summary>
            [RepositoryItem("f5ba786b-515e-45ce-983e-13f0acf2602e")]
            public virtual Ranorex.SpanTag RIView_StatusClosed_Badge
            {
                get
                {
                    return _riview_statusclosed_badgeInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The RIView_StatusClosed_Badge item info.
            /// </summary>
            [RepositoryItemInfo("f5ba786b-515e-45ce-983e-13f0acf2602e")]
            public virtual RepoItemInfo RIView_StatusClosed_BadgeInfo
            {
                get
                {
                    return _riview_statusclosed_badgeInfo;
                }
            }

            /// <summary>
            /// The RIView_Close_Btn item.
            /// </summary>
            [RepositoryItem("8ffe5cec-f581-41b9-ae0d-6c8317d3ac0e")]
            public virtual Ranorex.ButtonTag RIView_Close_Btn
            {
                get
                {
                    return _riview_close_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The RIView_Close_Btn item info.
            /// </summary>
            [RepositoryItemInfo("8ffe5cec-f581-41b9-ae0d-6c8317d3ac0e")]
            public virtual RepoItemInfo RIView_Close_BtnInfo
            {
                get
                {
                    return _riview_close_btnInfo;
                }
            }

            /// <summary>
            /// The RIView_Edit_Btn item.
            /// </summary>
            [RepositoryItem("fed90404-4bfb-4b0c-81fd-6b0aee3832e0")]
            public virtual Ranorex.Button RIView_Edit_Btn
            {
                get
                {
                    return _riview_edit_btnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The RIView_Edit_Btn item info.
            /// </summary>
            [RepositoryItemInfo("fed90404-4bfb-4b0c-81fd-6b0aee3832e0")]
            public virtual RepoItemInfo RIView_Edit_BtnInfo
            {
                get
                {
                    return _riview_edit_btnInfo;
                }
            }

            /// <summary>
            /// The Survey_Question1_TextInput item.
            /// </summary>
            [RepositoryItem("c2e8bccf-a1b0-482e-911f-aa9f7213bc41")]
            public virtual Ranorex.BodyTag Survey_Question1_TextInput
            {
                get
                {
                    return _survey_question1_textinputInfo.CreateAdapter<Ranorex.BodyTag>(true);
                }
            }

            /// <summary>
            /// The Survey_Question1_TextInput item info.
            /// </summary>
            [RepositoryItemInfo("c2e8bccf-a1b0-482e-911f-aa9f7213bc41")]
            public virtual RepoItemInfo Survey_Question1_TextInputInfo
            {
                get
                {
                    return _survey_question1_textinputInfo;
                }
            }

            /// <summary>
            /// The Survey_Question1_Yes item.
            /// </summary>
            [RepositoryItem("4502579e-a5cf-4155-a858-cbe383a6349c")]
            public virtual Ranorex.DivTag Survey_Question1_Yes
            {
                get
                {
                    return _survey_question1_yesInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The Survey_Question1_Yes item info.
            /// </summary>
            [RepositoryItemInfo("4502579e-a5cf-4155-a858-cbe383a6349c")]
            public virtual RepoItemInfo Survey_Question1_YesInfo
            {
                get
                {
                    return _survey_question1_yesInfo;
                }
            }

            /// <summary>
            /// The Survey_Question1_Yes_Tick item.
            /// </summary>
            [RepositoryItem("59ab7194-b16d-432e-a6ae-fc7a86824abf")]
            public virtual Ranorex.ITag Survey_Question1_Yes_Tick
            {
                get
                {
                    return _survey_question1_yes_tickInfo.CreateAdapter<Ranorex.ITag>(true);
                }
            }

            /// <summary>
            /// The Survey_Question1_Yes_Tick item info.
            /// </summary>
            [RepositoryItemInfo("59ab7194-b16d-432e-a6ae-fc7a86824abf")]
            public virtual RepoItemInfo Survey_Question1_Yes_TickInfo
            {
                get
                {
                    return _survey_question1_yes_tickInfo;
                }
            }

            /// <summary>
            /// The Survey_Section_ExecutiveSummary item.
            /// </summary>
            [RepositoryItem("84246a39-7014-485e-9a7a-d0c1faeb711b")]
            public virtual Ranorex.SpanTag Survey_Section_ExecutiveSummary
            {
                get
                {
                    return _survey_section_executivesummaryInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Survey_Section_ExecutiveSummary item info.
            /// </summary>
            [RepositoryItemInfo("84246a39-7014-485e-9a7a-d0c1faeb711b")]
            public virtual RepoItemInfo Survey_Section_ExecutiveSummaryInfo
            {
                get
                {
                    return _survey_section_executivesummaryInfo;
                }
            }

            /// <summary>
            /// The Survey_Next_Btn item.
            /// </summary>
            [RepositoryItem("31b0d766-dc60-45d6-b004-31e7da5b2d4a")]
            public virtual Ranorex.Button Survey_Next_Btn
            {
                get
                {
                    return _survey_next_btnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Survey_Next_Btn item info.
            /// </summary>
            [RepositoryItemInfo("31b0d766-dc60-45d6-b004-31e7da5b2d4a")]
            public virtual RepoItemInfo Survey_Next_BtnInfo
            {
                get
                {
                    return _survey_next_btnInfo;
                }
            }

            /// <summary>
            /// The Survey_Previous_Btn item.
            /// </summary>
            [RepositoryItem("f3849c5e-d3b8-4c28-8e10-0d9cf810dbfc")]
            public virtual Ranorex.Button Survey_Previous_Btn
            {
                get
                {
                    return _survey_previous_btnInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Survey_Previous_Btn item info.
            /// </summary>
            [RepositoryItemInfo("f3849c5e-d3b8-4c28-8e10-0d9cf810dbfc")]
            public virtual RepoItemInfo Survey_Previous_BtnInfo
            {
                get
                {
                    return _survey_previous_btnInfo;
                }
            }

            /// <summary>
            /// The QuestionOneAnswerText item.
            /// </summary>
            [RepositoryItem("67c6dc48-e472-4c95-bf5a-91b9f5ac8982")]
            public virtual Ranorex.PTag QuestionOneAnswerText
            {
                get
                {
                    return _questiononeanswertextInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The QuestionOneAnswerText item info.
            /// </summary>
            [RepositoryItemInfo("67c6dc48-e472-4c95-bf5a-91b9f5ac8982")]
            public virtual RepoItemInfo QuestionOneAnswerTextInfo
            {
                get
                {
                    return _questiononeanswertextInfo;
                }
            }

            /// <summary>
            /// The QuestionAddPhoto item.
            /// </summary>
            [RepositoryItem("17952ccf-47b6-484d-8247-c10c20ed1a40")]
            public virtual Ranorex.DivTag QuestionAddPhoto
            {
                get
                {
                    return _questionaddphotoInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The QuestionAddPhoto item info.
            /// </summary>
            [RepositoryItemInfo("17952ccf-47b6-484d-8247-c10c20ed1a40")]
            public virtual RepoItemInfo QuestionAddPhotoInfo
            {
                get
                {
                    return _questionaddphotoInfo;
                }
            }

            /// <summary>
            /// The AddAttachments_DropFilesHereToUpload_Text item.
            /// </summary>
            [RepositoryItem("d86c6774-87b7-4ae5-bda7-82d05a281ed3")]
            public virtual Ranorex.ButtonTag AddAttachments_DropFilesHereToUpload_Text
            {
                get
                {
                    return _addattachments_dropfilesheretoupload_textInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The AddAttachments_DropFilesHereToUpload_Text item info.
            /// </summary>
            [RepositoryItemInfo("d86c6774-87b7-4ae5-bda7-82d05a281ed3")]
            public virtual RepoItemInfo AddAttachments_DropFilesHereToUpload_TextInfo
            {
                get
                {
                    return _addattachments_dropfilesheretoupload_textInfo;
                }
            }

            /// <summary>
            /// The Survey_Print_Btn item.
            /// </summary>
            [RepositoryItem("4fd1aed3-b494-42f5-acb6-fa97c02bcbbc")]
            public virtual Ranorex.SpanTag Survey_Print_Btn
            {
                get
                {
                    return _survey_print_btnInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Survey_Print_Btn item info.
            /// </summary>
            [RepositoryItemInfo("4fd1aed3-b494-42f5-acb6-fa97c02bcbbc")]
            public virtual RepoItemInfo Survey_Print_BtnInfo
            {
                get
                {
                    return _survey_print_btnInfo;
                }
            }

            /// <summary>
            /// The Export_Modal_HeaderText item.
            /// </summary>
            [RepositoryItem("36ef6eeb-98c4-4602-b1bc-f38f37ec0891")]
            public virtual Ranorex.H5Tag Export_Modal_HeaderText
            {
                get
                {
                    return _export_modal_headertextInfo.CreateAdapter<Ranorex.H5Tag>(true);
                }
            }

            /// <summary>
            /// The Export_Modal_HeaderText item info.
            /// </summary>
            [RepositoryItemInfo("36ef6eeb-98c4-4602-b1bc-f38f37ec0891")]
            public virtual RepoItemInfo Export_Modal_HeaderTextInfo
            {
                get
                {
                    return _export_modal_headertextInfo;
                }
            }

            /// <summary>
            /// The Export_Modal_DownloadPDF_Btn item.
            /// </summary>
            [RepositoryItem("c14a6f2c-954f-4e99-aee9-62411a137634")]
            public virtual Ranorex.ATag Export_Modal_DownloadPDF_Btn
            {
                get
                {
                    return _export_modal_downloadpdf_btnInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Export_Modal_DownloadPDF_Btn item info.
            /// </summary>
            [RepositoryItemInfo("c14a6f2c-954f-4e99-aee9-62411a137634")]
            public virtual RepoItemInfo Export_Modal_DownloadPDF_BtnInfo
            {
                get
                {
                    return _export_modal_downloadpdf_btnInfo;
                }
            }

            /// <summary>
            /// The Navbar_SignedInUser item.
            /// </summary>
            [RepositoryItem("36dbab1f-5de6-4f08-b959-de47d427e321")]
            public virtual Ranorex.LiTag Navbar_SignedInUser
            {
                get
                {
                    return _navbar_signedinuserInfo.CreateAdapter<Ranorex.LiTag>(true);
                }
            }

            /// <summary>
            /// The Navbar_SignedInUser item info.
            /// </summary>
            [RepositoryItemInfo("36dbab1f-5de6-4f08-b959-de47d427e321")]
            public virtual RepoItemInfo Navbar_SignedInUserInfo
            {
                get
                {
                    return _navbar_signedinuserInfo;
                }
            }

            /// <summary>
            /// The SignOut item.
            /// </summary>
            [RepositoryItem("79fbad80-48aa-454c-8e91-3c7b24be5cfd")]
            public virtual Ranorex.ATag SignOut
            {
                get
                {
                    return _signoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SignOut item info.
            /// </summary>
            [RepositoryItemInfo("79fbad80-48aa-454c-8e91-3c7b24be5cfd")]
            public virtual RepoItemInfo SignOutInfo
            {
                get
                {
                    return _signoutInfo;
                }
            }

            /// <summary>
            /// The Survey_Submit_Btn item.
            /// </summary>
            [RepositoryItem("5a4317f4-cf50-4902-9170-7a3ba11e86d2")]
            public virtual Ranorex.SpanTag Survey_Submit_Btn
            {
                get
                {
                    return _survey_submit_btnInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Survey_Submit_Btn item info.
            /// </summary>
            [RepositoryItemInfo("5a4317f4-cf50-4902-9170-7a3ba11e86d2")]
            public virtual RepoItemInfo Survey_Submit_BtnInfo
            {
                get
                {
                    return _survey_submit_btnInfo;
                }
            }

            /// <summary>
            /// The Yes item.
            /// </summary>
            [RepositoryItem("f1606ed2-32dd-48e0-8457-7be0d2beedcf")]
            public virtual Ranorex.ButtonTag Yes
            {
                get
                {
                    return _yesInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The Yes item info.
            /// </summary>
            [RepositoryItemInfo("f1606ed2-32dd-48e0-8457-7be0d2beedcf")]
            public virtual RepoItemInfo YesInfo
            {
                get
                {
                    return _yesInfo;
                }
            }

            /// <summary>
            /// The Confirmation_Modal_HeaderText item.
            /// </summary>
            [RepositoryItem("282180d7-ce0d-45cf-8ec7-ec2f06bd5618")]
            public virtual Ranorex.H5Tag Confirmation_Modal_HeaderText
            {
                get
                {
                    return _confirmation_modal_headertextInfo.CreateAdapter<Ranorex.H5Tag>(true);
                }
            }

            /// <summary>
            /// The Confirmation_Modal_HeaderText item info.
            /// </summary>
            [RepositoryItemInfo("282180d7-ce0d-45cf-8ec7-ec2f06bd5618")]
            public virtual RepoItemInfo Confirmation_Modal_HeaderTextInfo
            {
                get
                {
                    return _confirmation_modal_headertextInfo;
                }
            }

            /// <summary>
            /// The AreYouSureYouWantToSubmit item.
            /// </summary>
            [RepositoryItem("093753d7-d09d-41ba-a55d-941dc0ecc220")]
            public virtual Ranorex.PTag AreYouSureYouWantToSubmit
            {
                get
                {
                    return _areyousureyouwanttosubmitInfo.CreateAdapter<Ranorex.PTag>(true);
                }
            }

            /// <summary>
            /// The AreYouSureYouWantToSubmit item info.
            /// </summary>
            [RepositoryItemInfo("093753d7-d09d-41ba-a55d-941dc0ecc220")]
            public virtual RepoItemInfo AreYouSureYouWantToSubmitInfo
            {
                get
                {
                    return _areyousureyouwanttosubmitInfo;
                }
            }

            /// <summary>
            /// The ReportSubmitted_Modal_HeaderText item.
            /// </summary>
            [RepositoryItem("2ca9d6c3-d076-404d-8e1b-739d90dd57cd")]
            public virtual Ranorex.H5Tag ReportSubmitted_Modal_HeaderText
            {
                get
                {
                    return _reportsubmitted_modal_headertextInfo.CreateAdapter<Ranorex.H5Tag>(true);
                }
            }

            /// <summary>
            /// The ReportSubmitted_Modal_HeaderText item info.
            /// </summary>
            [RepositoryItemInfo("2ca9d6c3-d076-404d-8e1b-739d90dd57cd")]
            public virtual RepoItemInfo ReportSubmitted_Modal_HeaderTextInfo
            {
                get
                {
                    return _reportsubmitted_modal_headertextInfo;
                }
            }

            /// <summary>
            /// The ReportSubmitted_Modal_ViewDetails_Btn item.
            /// </summary>
            [RepositoryItem("55d08da7-2a21-4f8b-bb47-d5bdff6f2714")]
            public virtual Ranorex.ButtonTag ReportSubmitted_Modal_ViewDetails_Btn
            {
                get
                {
                    return _reportsubmitted_modal_viewdetails_btnInfo.CreateAdapter<Ranorex.ButtonTag>(true);
                }
            }

            /// <summary>
            /// The ReportSubmitted_Modal_ViewDetails_Btn item info.
            /// </summary>
            [RepositoryItemInfo("55d08da7-2a21-4f8b-bb47-d5bdff6f2714")]
            public virtual RepoItemInfo ReportSubmitted_Modal_ViewDetails_BtnInfo
            {
                get
                {
                    return _reportsubmitted_modal_viewdetails_btnInfo;
                }
            }

            /// <summary>
            /// The Activity_InternalStatus item.
            /// </summary>
            [RepositoryItem("32d4bf33-8746-4e21-a5a6-72d05c316ce9")]
            public virtual Ranorex.SpanTag Activity_InternalStatus
            {
                get
                {
                    return _activity_internalstatusInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Activity_InternalStatus item info.
            /// </summary>
            [RepositoryItemInfo("32d4bf33-8746-4e21-a5a6-72d05c316ce9")]
            public virtual RepoItemInfo Activity_InternalStatusInfo
            {
                get
                {
                    return _activity_internalstatusInfo;
                }
            }

            /// <summary>
            /// The Activity_Search item.
            /// </summary>
            [RepositoryItem("1d377535-72b6-475d-b0b4-6686680b2f33")]
            public virtual Ranorex.InputTag Activity_Search
            {
                get
                {
                    return _activity_searchInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The Activity_Search item info.
            /// </summary>
            [RepositoryItemInfo("1d377535-72b6-475d-b0b4-6686680b2f33")]
            public virtual RepoItemInfo Activity_SearchInfo
            {
                get
                {
                    return _activity_searchInfo;
                }
            }
        }

        /// <summary>
        /// The OpenAppFolder folder.
        /// </summary>
        [RepositoryFolder("984269d3-b34a-4ce4-9325-cf7a1de97550")]
        public partial class OpenAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _cancelInfo;

            /// <summary>
            /// Creates a new Open  folder.
            /// </summary>
            public OpenAppFolder(RepoGenBaseFolder parentFolder) :
                    base("Open", "/form[@title='Open' or @title='Save As']", parentFolder, 30000, null, true, "984269d3-b34a-4ce4-9325-cf7a1de97550", "")
            {
                _cancelInfo = new RepoItemInfo(this, "Cancel", "button[@controlid='2']", "button[@controlid='2']", 1000, null, "fe5e03b9-251c-44ae-be05-5ae171aff60d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("984269d3-b34a-4ce4-9325-cf7a1de97550")]
            public virtual Ranorex.Form Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.Form>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("984269d3-b34a-4ce4-9325-cf7a1de97550")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The Cancel item.
            /// </summary>
            [RepositoryItem("fe5e03b9-251c-44ae-be05-5ae171aff60d")]
            public virtual Ranorex.Button Cancel
            {
                get
                {
                    return _cancelInfo.CreateAdapter<Ranorex.Button>(true);
                }
            }

            /// <summary>
            /// The Cancel item info.
            /// </summary>
            [RepositoryItemInfo("fe5e03b9-251c-44ae-be05-5ae171aff60d")]
            public virtual RepoItemInfo CancelInfo
            {
                get
                {
                    return _cancelInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
