///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Drawing;
using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Repository;
using Ranorex.Core.Testing;

namespace BackOffice
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    /// The class representing the _MemberPortalRepository element repository.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    [RepositoryFolder("e2760953-94c5-4dd9-9d48-718a4684154f")]
    public partial class _MemberPortalRepository : RepoGenBaseFolder
    {
        static _MemberPortalRepository instance = new _MemberPortalRepository();
        _MemberPortalRepositoryFolders.MemberPortalAppFolder _memberportal;
        _MemberPortalRepositoryFolders.IdentityUsaDevRisksolvedComAppFolder _identityusadevrisksolvedcom;

        /// <summary>
        /// Gets the singleton class instance representing the _MemberPortalRepository element repository.
        /// </summary>
        [RepositoryFolder("e2760953-94c5-4dd9-9d48-718a4684154f")]
        public static _MemberPortalRepository Instance
        {
            get { return instance; }
        }

        /// <summary>
        /// Repository class constructor.
        /// </summary>
        public _MemberPortalRepository() 
            : base("_MemberPortalRepository", "/", null, 0, false, "e2760953-94c5-4dd9-9d48-718a4684154f", ".\\RepositoryImages\\_MemberPortalRepositorye2760953.rximgres")
        {
            _memberportal = new _MemberPortalRepositoryFolders.MemberPortalAppFolder(this);
            _identityusadevrisksolvedcom = new _MemberPortalRepositoryFolders.IdentityUsaDevRisksolvedComAppFolder(this);
        }

#region Variables

#endregion

        /// <summary>
        /// The Self item info.
        /// </summary>
        [RepositoryItemInfo("e2760953-94c5-4dd9-9d48-718a4684154f")]
        public virtual RepoItemInfo SelfInfo
        {
            get
            {
                return _selfInfo;
            }
        }

        /// <summary>
        /// The MemberPortal folder.
        /// </summary>
        [RepositoryFolder("4fac7ba2-e16b-406e-9e0d-012351a834af")]
        public virtual _MemberPortalRepositoryFolders.MemberPortalAppFolder MemberPortal
        {
            get { return _memberportal; }
        }

        /// <summary>
        /// The IdentityUsaDevRisksolvedCom folder.
        /// </summary>
        [RepositoryFolder("409a9c09-94d7-4578-9f8d-bb3663429098")]
        public virtual _MemberPortalRepositoryFolders.IdentityUsaDevRisksolvedComAppFolder IdentityUsaDevRisksolvedCom
        {
            get { return _identityusadevrisksolvedcom; }
        }
    }

    /// <summary>
    /// Inner folder classes.
    /// </summary>
    [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
    public partial class _MemberPortalRepositoryFolders
    {
        /// <summary>
        /// The MemberPortalAppFolder folder.
        /// </summary>
        [RepositoryFolder("4fac7ba2-e16b-406e-9e0d-012351a834af")]
        public partial class MemberPortalAppFolder : RepoGenBaseFolder
        {
            RepoItemInfo _login_usernameInfo;
            RepoItemInfo _login_passwordInfo;
            RepoItemInfo _btnloginInfo;
            RepoItemInfo _welcomeInfo;
            RepoItemInfo _signoutInfo;
            RepoItemInfo _riskassessment_propertyInfo;
            RepoItemInfo _riskassessment_casualtyInfo;
            RepoItemInfo _dashboards_propertyInfo;
            RepoItemInfo _dashboards_casualtyInfo;
            RepoItemInfo _suggestions_propertyInfo;
            RepoItemInfo _suggestions_casualtyInfo;
            RepoItemInfo _navbar_homepageInfo;
            RepoItemInfo _results_grid_row1Info;
            RepoItemInfo _dashboardcontainerInfo;

            /// <summary>
            /// Creates a new MemberPortal  folder.
            /// </summary>
            public MemberPortalAppFolder(RepoGenBaseFolder parentFolder) :
                    base("MemberPortal", "/dom[@domain>'rslportal']", parentFolder, 5000, null, false, "4fac7ba2-e16b-406e-9e0d-012351a834af", "")
            {
                _login_usernameInfo = new RepoItemInfo(this, "LogIn_Username", ".//div[#'divLoginInner']/?/?/input[@name='ctl00$PlaceHolderMain$txtUser']", ".//div[#'divLoginInner']/?/?/input[@name='ctl00$PlaceHolderMain$txtUser']", 30000, null, "d7c5bec8-720f-420c-b3f6-288db1af6274");
                _login_passwordInfo = new RepoItemInfo(this, "LogIn_Password", ".//div[#'divLoginInner']/?/?/input[@name='ctl00$PlaceHolderMain$txtPassword']", ".//div[#'divLoginInner']/?/?/input[@name='ctl00$PlaceHolderMain$txtPassword']", 30000, null, "195ed1a1-899c-4e93-93ea-73158b1375d9");
                _btnloginInfo = new RepoItemInfo(this, "BtnLogin", ".//input[#'btnLogin']", ".//input[#'btnLogin']", 30000, null, "23f92129-06a7-4b78-bdec-8195bbb919ef");
                _welcomeInfo = new RepoItemInfo(this, "Welcome", ".//div[#'nav']//span[@innertext>'Welcome']", ".//div[#'nav']//span[@innertext='Welcome Steve Demo']", 30000, null, "25491106-1d2b-452d-85bd-ac2a6cbda909");
                _signoutInfo = new RepoItemInfo(this, "SignOut", ".//div[#'nav']//a[@innertext='Sign out']", ".//div[#'nav']//a[@innertext='Sign out']", 30000, null, "57cea7f8-b1e4-43ec-ab5c-aa1e71ac3686");
                _riskassessment_propertyInfo = new RepoItemInfo(this, "RiskAssessment_Property", ".//div[#'tile-container']//a[@innertext='Property']", ".//div[#'tile-container']//a[@innertext='Property']", 30000, null, "da8f0414-7b6e-4d72-8d1f-ff4a1105efe4");
                _riskassessment_casualtyInfo = new RepoItemInfo(this, "RiskAssessment_Casualty", ".//div[#'tile-container']//a[@innertext='Casualty']", ".//div[#'tile-container']//a[@innertext='Property']", 30000, null, "7213b8a4-0c45-4aa1-a5a9-5fbc071726e7");
                _dashboards_propertyInfo = new RepoItemInfo(this, "Dashboards_Property", ".//div[#'tile-container']/div[2]/div/div[4]/div[2]/a[@innertext='Property']", ".//div[#'tile-container']/div[2]/div/div[4]/div[2]/a[@innertext='Property']", 30000, null, "79c849b9-4f17-47c1-b223-25b5b0b4bbb2");
                _dashboards_casualtyInfo = new RepoItemInfo(this, "Dashboards_Casualty", ".//div[#'tile-container']/div[2]/div/div[4]/div[2]/a[@innertext='Casualty']", ".//div[#'tile-container']/div[2]/div/div[4]/div[2]/a[@innertext='Property']", 30000, null, "4db1517c-a269-444e-823e-9cc630b687e2");
                _suggestions_propertyInfo = new RepoItemInfo(this, "Suggestions_Property", ".//div[#'tile-container']/div[2]/div/div[3]/div[2]/a[@innertext='Property']", ".//div[#'tile-container']/div[2]/div/div[3]/div[2]/a[@innertext='Property']", 30000, null, "7bea6264-4fc1-416e-ba76-850eb2caaa06");
                _suggestions_casualtyInfo = new RepoItemInfo(this, "Suggestions_Casualty", ".//div[#'tile-container']/div[2]/div/div[3]/div[2]/a[@innertext='Casualty']", ".//div[#'tile-container']/div[2]/div/div[3]/div[2]/a[@innertext='Property']", 30000, null, "d09e3a27-876b-4b52-bd98-a6069e317a86");
                _navbar_homepageInfo = new RepoItemInfo(this, "Navbar_Homepage", ".//div[#'nav']//a[@innertext='Homepage']", ".//div[#'nav']//a[@innertext='Homepage']", 30000, null, "06086714-3e91-4c88-b903-1f693e200432");
                _results_grid_row1Info = new RepoItemInfo(this, "Results_Grid_Row1", ".//table[#'activityTable_header']/tbody/tr[1]", ".//table[#'activityTable_header']/tbody/tr[1]", 1000, null, "7804d0d9-504b-4ade-a636-02d8fd964040");
                _dashboardcontainerInfo = new RepoItemInfo(this, "DashboardContainer", ".//div[#'reportContainer']", ".//div[#'reportContainer']", 1000, null, "44e555fa-893b-490c-8ba0-68ac27c6876d");
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("4fac7ba2-e16b-406e-9e0d-012351a834af")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("4fac7ba2-e16b-406e-9e0d-012351a834af")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }

            /// <summary>
            /// The LogIn_Username item.
            /// </summary>
            [RepositoryItem("d7c5bec8-720f-420c-b3f6-288db1af6274")]
            public virtual Ranorex.InputTag LogIn_Username
            {
                get
                {
                    return _login_usernameInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LogIn_Username item info.
            /// </summary>
            [RepositoryItemInfo("d7c5bec8-720f-420c-b3f6-288db1af6274")]
            public virtual RepoItemInfo LogIn_UsernameInfo
            {
                get
                {
                    return _login_usernameInfo;
                }
            }

            /// <summary>
            /// The LogIn_Password item.
            /// </summary>
            [RepositoryItem("195ed1a1-899c-4e93-93ea-73158b1375d9")]
            public virtual Ranorex.InputTag LogIn_Password
            {
                get
                {
                    return _login_passwordInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The LogIn_Password item info.
            /// </summary>
            [RepositoryItemInfo("195ed1a1-899c-4e93-93ea-73158b1375d9")]
            public virtual RepoItemInfo LogIn_PasswordInfo
            {
                get
                {
                    return _login_passwordInfo;
                }
            }

            /// <summary>
            /// The BtnLogin item.
            /// </summary>
            [RepositoryItem("23f92129-06a7-4b78-bdec-8195bbb919ef")]
            public virtual Ranorex.InputTag BtnLogin
            {
                get
                {
                    return _btnloginInfo.CreateAdapter<Ranorex.InputTag>(true);
                }
            }

            /// <summary>
            /// The BtnLogin item info.
            /// </summary>
            [RepositoryItemInfo("23f92129-06a7-4b78-bdec-8195bbb919ef")]
            public virtual RepoItemInfo BtnLoginInfo
            {
                get
                {
                    return _btnloginInfo;
                }
            }

            /// <summary>
            /// The Welcome item.
            /// </summary>
            [RepositoryItem("25491106-1d2b-452d-85bd-ac2a6cbda909")]
            public virtual Ranorex.SpanTag Welcome
            {
                get
                {
                    return _welcomeInfo.CreateAdapter<Ranorex.SpanTag>(true);
                }
            }

            /// <summary>
            /// The Welcome item info.
            /// </summary>
            [RepositoryItemInfo("25491106-1d2b-452d-85bd-ac2a6cbda909")]
            public virtual RepoItemInfo WelcomeInfo
            {
                get
                {
                    return _welcomeInfo;
                }
            }

            /// <summary>
            /// The SignOut item.
            /// </summary>
            [RepositoryItem("57cea7f8-b1e4-43ec-ab5c-aa1e71ac3686")]
            public virtual Ranorex.ATag SignOut
            {
                get
                {
                    return _signoutInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The SignOut item info.
            /// </summary>
            [RepositoryItemInfo("57cea7f8-b1e4-43ec-ab5c-aa1e71ac3686")]
            public virtual RepoItemInfo SignOutInfo
            {
                get
                {
                    return _signoutInfo;
                }
            }

            /// <summary>
            /// The RiskAssessment_Property item.
            /// </summary>
            [RepositoryItem("da8f0414-7b6e-4d72-8d1f-ff4a1105efe4")]
            public virtual Ranorex.ATag RiskAssessment_Property
            {
                get
                {
                    return _riskassessment_propertyInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The RiskAssessment_Property item info.
            /// </summary>
            [RepositoryItemInfo("da8f0414-7b6e-4d72-8d1f-ff4a1105efe4")]
            public virtual RepoItemInfo RiskAssessment_PropertyInfo
            {
                get
                {
                    return _riskassessment_propertyInfo;
                }
            }

            /// <summary>
            /// The RiskAssessment_Casualty item.
            /// </summary>
            [RepositoryItem("7213b8a4-0c45-4aa1-a5a9-5fbc071726e7")]
            public virtual Ranorex.ATag RiskAssessment_Casualty
            {
                get
                {
                    return _riskassessment_casualtyInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The RiskAssessment_Casualty item info.
            /// </summary>
            [RepositoryItemInfo("7213b8a4-0c45-4aa1-a5a9-5fbc071726e7")]
            public virtual RepoItemInfo RiskAssessment_CasualtyInfo
            {
                get
                {
                    return _riskassessment_casualtyInfo;
                }
            }

            /// <summary>
            /// The Dashboards_Property item.
            /// </summary>
            [RepositoryItem("79c849b9-4f17-47c1-b223-25b5b0b4bbb2")]
            public virtual Ranorex.ATag Dashboards_Property
            {
                get
                {
                    return _dashboards_propertyInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Dashboards_Property item info.
            /// </summary>
            [RepositoryItemInfo("79c849b9-4f17-47c1-b223-25b5b0b4bbb2")]
            public virtual RepoItemInfo Dashboards_PropertyInfo
            {
                get
                {
                    return _dashboards_propertyInfo;
                }
            }

            /// <summary>
            /// The Dashboards_Casualty item.
            /// </summary>
            [RepositoryItem("4db1517c-a269-444e-823e-9cc630b687e2")]
            public virtual Ranorex.ATag Dashboards_Casualty
            {
                get
                {
                    return _dashboards_casualtyInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Dashboards_Casualty item info.
            /// </summary>
            [RepositoryItemInfo("4db1517c-a269-444e-823e-9cc630b687e2")]
            public virtual RepoItemInfo Dashboards_CasualtyInfo
            {
                get
                {
                    return _dashboards_casualtyInfo;
                }
            }

            /// <summary>
            /// The Suggestions_Property item.
            /// </summary>
            [RepositoryItem("7bea6264-4fc1-416e-ba76-850eb2caaa06")]
            public virtual Ranorex.ATag Suggestions_Property
            {
                get
                {
                    return _suggestions_propertyInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Suggestions_Property item info.
            /// </summary>
            [RepositoryItemInfo("7bea6264-4fc1-416e-ba76-850eb2caaa06")]
            public virtual RepoItemInfo Suggestions_PropertyInfo
            {
                get
                {
                    return _suggestions_propertyInfo;
                }
            }

            /// <summary>
            /// The Suggestions_Casualty item.
            /// </summary>
            [RepositoryItem("d09e3a27-876b-4b52-bd98-a6069e317a86")]
            public virtual Ranorex.ATag Suggestions_Casualty
            {
                get
                {
                    return _suggestions_casualtyInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Suggestions_Casualty item info.
            /// </summary>
            [RepositoryItemInfo("d09e3a27-876b-4b52-bd98-a6069e317a86")]
            public virtual RepoItemInfo Suggestions_CasualtyInfo
            {
                get
                {
                    return _suggestions_casualtyInfo;
                }
            }

            /// <summary>
            /// The Navbar_Homepage item.
            /// </summary>
            [RepositoryItem("06086714-3e91-4c88-b903-1f693e200432")]
            public virtual Ranorex.ATag Navbar_Homepage
            {
                get
                {
                    return _navbar_homepageInfo.CreateAdapter<Ranorex.ATag>(true);
                }
            }

            /// <summary>
            /// The Navbar_Homepage item info.
            /// </summary>
            [RepositoryItemInfo("06086714-3e91-4c88-b903-1f693e200432")]
            public virtual RepoItemInfo Navbar_HomepageInfo
            {
                get
                {
                    return _navbar_homepageInfo;
                }
            }

            /// <summary>
            /// The Results_Grid_Row1 item.
            /// </summary>
            [RepositoryItem("7804d0d9-504b-4ade-a636-02d8fd964040")]
            public virtual Ranorex.TrTag Results_Grid_Row1
            {
                get
                {
                    return _results_grid_row1Info.CreateAdapter<Ranorex.TrTag>(true);
                }
            }

            /// <summary>
            /// The Results_Grid_Row1 item info.
            /// </summary>
            [RepositoryItemInfo("7804d0d9-504b-4ade-a636-02d8fd964040")]
            public virtual RepoItemInfo Results_Grid_Row1Info
            {
                get
                {
                    return _results_grid_row1Info;
                }
            }

            /// <summary>
            /// The DashboardContainer item.
            /// </summary>
            [RepositoryItem("44e555fa-893b-490c-8ba0-68ac27c6876d")]
            public virtual Ranorex.DivTag DashboardContainer
            {
                get
                {
                    return _dashboardcontainerInfo.CreateAdapter<Ranorex.DivTag>(true);
                }
            }

            /// <summary>
            /// The DashboardContainer item info.
            /// </summary>
            [RepositoryItemInfo("44e555fa-893b-490c-8ba0-68ac27c6876d")]
            public virtual RepoItemInfo DashboardContainerInfo
            {
                get
                {
                    return _dashboardcontainerInfo;
                }
            }
        }

        /// <summary>
        /// The IdentityUsaDevRisksolvedComAppFolder folder.
        /// </summary>
        [RepositoryFolder("409a9c09-94d7-4578-9f8d-bb3663429098")]
        public partial class IdentityUsaDevRisksolvedComAppFolder : RepoGenBaseFolder
        {

            /// <summary>
            /// Creates a new IdentityUsaDevRisksolvedCom  folder.
            /// </summary>
            public IdentityUsaDevRisksolvedComAppFolder(RepoGenBaseFolder parentFolder) :
                    base("IdentityUsaDevRisksolvedCom", "/dom[@domain='identity-usa-dev.risksolved.com' or @domain='identity-usa-uat.risksolved.com']", parentFolder, 10000, null, false, "409a9c09-94d7-4578-9f8d-bb3663429098", "")
            {
            }

            /// <summary>
            /// The Self item.
            /// </summary>
            [RepositoryItem("409a9c09-94d7-4578-9f8d-bb3663429098")]
            public virtual Ranorex.WebDocument Self
            {
                get
                {
                    return _selfInfo.CreateAdapter<Ranorex.WebDocument>(true);
                }
            }

            /// <summary>
            /// The Self item info.
            /// </summary>
            [RepositoryItemInfo("409a9c09-94d7-4578-9f8d-bb3663429098")]
            public virtual RepoItemInfo SelfInfo
            {
                get
                {
                    return _selfInfo;
                }
            }
        }

    }
#pragma warning restore 0436
}
