///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BackOffice
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BackOffice_ExternalUser_Set_ConsultantPortalUser_True recording.
    /// </summary>
    [TestModule("d3638962-65d0-4319-a077-20d82e1ae2ff", ModuleType.Recording, 1)]
    public partial class BackOffice_ExternalUser_Set_ConsultantPortalUser_True : ITestModule
    {
        /// <summary>
        /// Holds an instance of the _BackOfficeRepository repository.
        /// </summary>
        public static _BackOfficeRepository repo = _BackOfficeRepository.Instance;

        static BackOffice_ExternalUser_Set_ConsultantPortalUser_True instance = new BackOffice_ExternalUser_Set_ConsultantPortalUser_True();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BackOffice_ExternalUser_Set_ConsultantPortalUser_True()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BackOffice_ExternalUser_Set_ConsultantPortalUser_True Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 300;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Set value", "Setting attribute Checked to 'True' on item 'BackOffice.ConsultantPortalUser'.", repo.BackOffice.ConsultantPortalUserInfo, new RecordItemIndex(0));
            repo.BackOffice.ConsultantPortalUser.Element.SetAttributeValue("Checked", "True");
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
