///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BackOffice
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BackOffice_Validate_ActivityDetails_Status_Distributed recording.
    /// </summary>
    [TestModule("549d2936-666d-4d36-95fc-675444523a44", ModuleType.Recording, 1)]
    public partial class BackOffice_Validate_ActivityDetails_Status_Distributed : ITestModule
    {
        /// <summary>
        /// Holds an instance of the _BackOfficeRepository repository.
        /// </summary>
        public static _BackOfficeRepository repo = _BackOfficeRepository.Instance;

        static BackOffice_Validate_ActivityDetails_Status_Distributed instance = new BackOffice_Validate_ActivityDetails_Status_Distributed();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BackOffice_Validate_ActivityDetails_Status_Distributed()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BackOffice_Validate_ActivityDetails_Status_Distributed Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 300;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'BackOffice.ActivityDetails_ActivityStatusField_Distributed'", repo.BackOffice.ActivityDetails_ActivityStatusField_DistributedInfo, new ActionTimeout(30000), new RecordItemIndex(0));
            repo.BackOffice.ActivityDetails_ActivityStatusField_DistributedInfo.WaitForExists(30000);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating AttributeEqual (InnerText='Distributed') on item 'BackOffice.ActivityDetails_ActivityStatusField_Distributed'.", repo.BackOffice.ActivityDetails_ActivityStatusField_DistributedInfo, new RecordItemIndex(1));
                Validate.AttributeEqual(repo.BackOffice.ActivityDetails_ActivityStatusField_DistributedInfo, "InnerText", "Distributed", null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(1)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
