///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BackOffice
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BackOffice_LogOut recording.
    /// </summary>
    [TestModule("a583ea15-650b-4ebd-88aa-e75d7cbced1b", ModuleType.Recording, 1)]
    public partial class BackOffice_LogOut : ITestModule
    {
        /// <summary>
        /// Holds an instance of the _BackOfficeRepository repository.
        /// </summary>
        public static _BackOfficeRepository repo = _BackOfficeRepository.Instance;

        static BackOffice_LogOut instance = new BackOffice_LogOut();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BackOffice_LogOut()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BackOffice_LogOut Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(0));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BackOffice.UserMenuItem' at Center.", repo.BackOffice.UserMenuItemInfo, new RecordItemIndex(1));
            repo.BackOffice.UserMenuItem.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BackOffice.UserMenuItem_LogoutButton' at Center.", repo.BackOffice.UserMenuItem_LogoutButtonInfo, new RecordItemIndex(2));
            repo.BackOffice.UserMenuItem_LogoutButton.Click();
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BackOffice.Logout_Btn' at Center.", repo.BackOffice.Logout_BtnInfo, new RecordItemIndex(3));
            repo.BackOffice.Logout_Btn.Click();
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m to not exist. Associated repository item: 'BackOffice.Loading_Modal'", repo.BackOffice.Loading_ModalInfo, new ActionTimeout(60000), new RecordItemIndex(4));
            repo.BackOffice.Loading_ModalInfo.WaitForNotExists(60000);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
