///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BackOffice
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BackOffice_Activities_ActivityDetailsTab recording.
    /// </summary>
    [TestModule("c7c1cc04-d830-4d64-afb8-4540ca124392", ModuleType.Recording, 1)]
    public partial class BackOffice_Activities_ActivityDetailsTab : ITestModule
    {
        /// <summary>
        /// Holds an instance of the _BackOfficeRepository repository.
        /// </summary>
        public static _BackOfficeRepository repo = _BackOfficeRepository.Instance;

        static BackOffice_Activities_ActivityDetailsTab instance = new BackOffice_Activities_ActivityDetailsTab();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BackOffice_Activities_ActivityDetailsTab()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BackOffice_Activities_ActivityDetailsTab Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BackOffice.Activites_ActivityDetailsTab' at Center.", repo.BackOffice.Activites_ActivityDetailsTabInfo, new RecordItemIndex(0));
            repo.BackOffice.Activites_ActivityDetailsTab.Click();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
