///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BackOffice
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BackOffice_ActivityUniqueID_Search_var recording.
    /// </summary>
    [TestModule("57792cf3-29f8-4b0f-afc6-94247da8b692", ModuleType.Recording, 1)]
    public partial class BackOffice_ActivityUniqueID_Search_var : ITestModule
    {
        /// <summary>
        /// Holds an instance of the _BackOfficeRepository repository.
        /// </summary>
        public static _BackOfficeRepository repo = _BackOfficeRepository.Instance;

        static BackOffice_ActivityUniqueID_Search_var instance = new BackOffice_ActivityUniqueID_Search_var();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BackOffice_ActivityUniqueID_Search_var()
        {
            ActivityNumber = "2500000089";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BackOffice_ActivityUniqueID_Search_var Instance
        {
            get { return instance; }
        }

#region Variables

        string _ActivityNumber;

        /// <summary>
        /// Gets or sets the value of variable ActivityNumber.
        /// </summary>
        [TestVariable("eab7311a-25d8-41de-ade1-2182d559b3b5")]
        public string ActivityNumber
        {
            get { return _ActivityNumber; }
            set { _ActivityNumber = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 300;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BackOffice.ActivityUniqueIDDisplayValue' at Center.", repo.BackOffice.ActivityUniqueIDDisplayValueInfo, new RecordItemIndex(0));
            repo.BackOffice.ActivityUniqueIDDisplayValue.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$ActivityNumber' with focus on 'BackOffice.ActivityUniqueIDDisplayValue'.", repo.BackOffice.ActivityUniqueIDDisplayValueInfo, new RecordItemIndex(1));
            repo.BackOffice.ActivityUniqueIDDisplayValue.PressKeys(ActivityNumber);
            Delay.Milliseconds(20);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Return}' with focus on 'BackOffice.ActivityUniqueIDDisplayValue'.", repo.BackOffice.ActivityUniqueIDDisplayValueInfo, new RecordItemIndex(2));
            repo.BackOffice.ActivityUniqueIDDisplayValue.EnsureVisible();
            Keyboard.Press("{Down}{Return}", 20);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
