///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BackOffice
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BackOffice_SignIn_Admin_var recording.
    /// </summary>
    [TestModule("802b90e2-c27a-4988-a1af-97ffd286f75d", ModuleType.Recording, 1)]
    public partial class BackOffice_SignIn_Admin_var : ITestModule
    {
        /// <summary>
        /// Holds an instance of the _BackOfficeRepository repository.
        /// </summary>
        public static _BackOfficeRepository repo = _BackOfficeRepository.Instance;

        static BackOffice_SignIn_Admin_var instance = new BackOffice_SignIn_Admin_var();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BackOffice_SignIn_Admin_var()
        {
            AdminLogin = "";
            AdminPassword = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BackOffice_SignIn_Admin_var Instance
        {
            get { return instance; }
        }

#region Variables

        string _AdminLogin;

        /// <summary>
        /// Gets or sets the value of variable AdminLogin.
        /// </summary>
        [TestVariable("f488b81c-3e01-4b8a-962e-f038f28a8e34")]
        public string AdminLogin
        {
            get { return _AdminLogin; }
            set { _AdminLogin = value; }
        }

        string _AdminPassword;

        /// <summary>
        /// Gets or sets the value of variable AdminPassword.
        /// </summary>
        [TestVariable("34fddd04-a8a3-4806-801f-ba0be7968c11")]
        public string AdminPassword
        {
            get { return _AdminPassword; }
            set { _AdminPassword = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BackOffice.UserName' at Center.", repo.BackOffice.UserNameInfo, new RecordItemIndex(0));
            repo.BackOffice.UserName.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$AdminLogin' with focus on 'BackOffice.UserName'.", repo.BackOffice.UserNameInfo, new RecordItemIndex(1));
            repo.BackOffice.UserName.PressKeys(AdminLogin);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BackOffice.Password' at Center.", repo.BackOffice.PasswordInfo, new RecordItemIndex(2));
            repo.BackOffice.Password.Click();
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$AdminPassword' with focus on 'BackOffice.Password'.", repo.BackOffice.PasswordInfo, new RecordItemIndex(3));
            repo.BackOffice.Password.PressKeys(AdminPassword);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BackOffice.LogIn_Btn' at Center.", repo.BackOffice.LogIn_BtnInfo, new RecordItemIndex(4));
            repo.BackOffice.LogIn_Btn.Click();
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'BackOffice'.", repo.BackOffice.SelfInfo, new RecordItemIndex(5));
            repo.BackOffice.Self.WaitForDocumentLoaded();
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
