///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BackOffice
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BackOffice_Search_Surname_ActivityID_ExternalUser recording.
    /// </summary>
    [TestModule("09f85fe8-9727-4056-8767-be1b71adc4fa", ModuleType.Recording, 1)]
    public partial class BackOffice_Search_Surname_ActivityID_ExternalUser : ITestModule
    {
        /// <summary>
        /// Holds an instance of the _BackOfficeRepository repository.
        /// </summary>
        public static _BackOfficeRepository repo = _BackOfficeRepository.Instance;

        static BackOffice_Search_Surname_ActivityID_ExternalUser instance = new BackOffice_Search_Surname_ActivityID_ExternalUser();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BackOffice_Search_Surname_ActivityID_ExternalUser()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BackOffice_Search_Surname_ActivityID_ExternalUser Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 300;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BackOffice.SurnameDisplayValue' at Center.", repo.BackOffice.SurnameDisplayValueInfo, new RecordItemIndex(0));
            repo.BackOffice.SurnameDisplayValue.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence 'Externaluser1' with focus on 'BackOffice.SurnameDisplayValue'.", repo.BackOffice.SurnameDisplayValueInfo, new RecordItemIndex(1));
            repo.BackOffice.SurnameDisplayValue.PressKeys("Externaluser1", 50);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 1s.", new RecordItemIndex(2));
            Delay.Duration(1000, false);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence '{Down}{Return}' with focus on 'BackOffice.SurnameDisplayValue'.", repo.BackOffice.SurnameDisplayValueInfo, new RecordItemIndex(3));
            repo.BackOffice.SurnameDisplayValue.EnsureVisible();
            Keyboard.Press("{Down}{Return}", 20);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
