///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BackOffice
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BackOffice_ResultsSummaryTab_Approve_Btn recording.
    /// </summary>
    [TestModule("412ef9f9-37a1-433b-b877-3b1a39b8a240", ModuleType.Recording, 1)]
    public partial class BackOffice_ResultsSummaryTab_Approve_Btn : ITestModule
    {
        /// <summary>
        /// Holds an instance of the _BackOfficeRepository repository.
        /// </summary>
        public static _BackOfficeRepository repo = _BackOfficeRepository.Instance;

        static BackOffice_ResultsSummaryTab_Approve_Btn instance = new BackOffice_ResultsSummaryTab_Approve_Btn();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BackOffice_ResultsSummaryTab_Approve_Btn()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BackOffice_ResultsSummaryTab_Approve_Btn Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 300;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Wait", "Waiting 1m to exist. Associated repository item: 'BackOffice.ResultsSummaryTab_Approve_Btn'", repo.BackOffice.ResultsSummaryTab_Approve_BtnInfo, new ActionTimeout(60000), new RecordItemIndex(0));
            repo.BackOffice.ResultsSummaryTab_Approve_BtnInfo.WaitForExists(60000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BackOffice.ResultsSummaryTab_Approve_Btn' at Center.", repo.BackOffice.ResultsSummaryTab_Approve_BtnInfo, new RecordItemIndex(1));
            repo.BackOffice.ResultsSummaryTab_Approve_Btn.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 2s.", new RecordItemIndex(2));
            Delay.Duration(2000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'BackOffice.ApproveActivity_Modal_Continue_Btn'", repo.BackOffice.ApproveActivity_Modal_Continue_BtnInfo, new ActionTimeout(30000), new RecordItemIndex(3));
            repo.BackOffice.ApproveActivity_Modal_Continue_BtnInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BackOffice.ApproveActivity_Modal_Continue_Btn' at Center.", repo.BackOffice.ApproveActivity_Modal_Continue_BtnInfo, new RecordItemIndex(4));
            repo.BackOffice.ApproveActivity_Modal_Continue_Btn.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Delay", "Waiting for 4s.", new RecordItemIndex(5));
            Delay.Duration(4000, false);
            
            Report.Log(ReportLevel.Info, "Wait", "Waiting 30s to exist. Associated repository item: 'BackOffice.ActivityHasBeenApproved_OK_Btn'", repo.BackOffice.ActivityHasBeenApproved_OK_BtnInfo, new ActionTimeout(30000), new RecordItemIndex(6));
            repo.BackOffice.ActivityHasBeenApproved_OK_BtnInfo.WaitForExists(30000);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'BackOffice.ActivityHasBeenApproved_OK_Btn' at Center.", repo.BackOffice.ActivityHasBeenApproved_OK_BtnInfo, new RecordItemIndex(7));
            repo.BackOffice.ActivityHasBeenApproved_OK_Btn.Click();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
