///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BackOffice
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The BackOffice_Launch_var recording.
    /// </summary>
    [TestModule("64c11f16-e805-4917-a0c8-210a7b287418", ModuleType.Recording, 1)]
    public partial class BackOffice_Launch_var : ITestModule
    {
        /// <summary>
        /// Holds an instance of the _BackOfficeRepository repository.
        /// </summary>
        public static _BackOfficeRepository repo = _BackOfficeRepository.Instance;

        static BackOffice_Launch_var instance = new BackOffice_Launch_var();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public BackOffice_Launch_var()
        {
            URL_BackOffice = "https://backoffice-dev-uk.risksolved.com/Login?org=NFUMUAT";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static BackOffice_Launch_var Instance
        {
            get { return instance; }
        }

#region Variables

        string _URL_BackOffice;

        /// <summary>
        /// Gets or sets the value of variable URL_BackOffice.
        /// </summary>
        [TestVariable("19e851bf-221d-4117-b7bb-1a3723d2f1c5")]
        public string URL_BackOffice
        {
            get { return _URL_BackOffice; }
            set { _URL_BackOffice = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 0;
            Keyboard.DefaultKeyPressTime = 20;
            Delay.SpeedFactor = 0.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Application", "(Optional Action)\r\nKilling application containing item 'BackOffice'.", repo.BackOffice.SelfInfo, new RecordItemIndex(0));
                Host.Current.KillApplication(repo.BackOffice.Self);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            Report.Log(ReportLevel.Info, "Website", "Opening web site URL in variable $URL_BackOffice in normal mode.", new RecordItemIndex(1));
            Host.Current.OpenBrowser(URL_BackOffice, "chrome", "", false, false, false, false, false, false, false, true);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
