///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BackOffice
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MemberPortal_Launch_var recording.
    /// </summary>
    [TestModule("697249f1-7078-4b88-9180-db04ba14960b", ModuleType.Recording, 1)]
    public partial class MemberPortal_Launch_var : ITestModule
    {
        /// <summary>
        /// Holds an instance of the _MemberPortalRepository repository.
        /// </summary>
        public static _MemberPortalRepository repo = _MemberPortalRepository.Instance;

        static MemberPortal_Launch_var instance = new MemberPortal_Launch_var();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MemberPortal_Launch_var()
        {
            URL_MemberPortal = "";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MemberPortal_Launch_var Instance
        {
            get { return instance; }
        }

#region Variables

        string _URL_MemberPortal;

        /// <summary>
        /// Gets or sets the value of variable URL_MemberPortal.
        /// </summary>
        [TestVariable("f66d0d3d-ff9e-4236-a1b4-68bc0fbe8607")]
        public string URL_MemberPortal
        {
            get { return _URL_MemberPortal; }
            set { _URL_MemberPortal = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 300;
            Delay.SpeedFactor = 1.00;

            Init();

            try {
                Report.Log(ReportLevel.Info, "Application", "(Optional Action)\r\nKilling application containing item 'MemberPortal'.", repo.MemberPortal.SelfInfo, new RecordItemIndex(0));
                Host.Current.KillApplication(repo.MemberPortal.Self);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(0)); }
            
            Report.Log(ReportLevel.Info, "Website", "Opening web site URL in variable $URL_MemberPortal in normal mode.", new RecordItemIndex(1));
            Host.Current.OpenBrowser(URL_MemberPortal, "Chrome", "", false, false, false, false, false, false, false, true);
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
