///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BackOffice
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MemberPortal_RiskAssessment_Casualty_Btn recording.
    /// </summary>
    [TestModule("0c79d550-92cc-4193-bda9-4a7597388bf9", ModuleType.Recording, 1)]
    public partial class MemberPortal_RiskAssessment_Casualty_Btn : ITestModule
    {
        /// <summary>
        /// Holds an instance of the _MemberPortalRepository repository.
        /// </summary>
        public static _MemberPortalRepository repo = _MemberPortalRepository.Instance;

        static MemberPortal_RiskAssessment_Casualty_Btn instance = new MemberPortal_RiskAssessment_Casualty_Btn();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MemberPortal_RiskAssessment_Casualty_Btn()
        {
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MemberPortal_RiskAssessment_Casualty_Btn Instance
        {
            get { return instance; }
        }

#region Variables

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 300;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemberPortal.RiskAssessment_Casualty' at Center.", repo.MemberPortal.RiskAssessment_CasualtyInfo, new RecordItemIndex(0));
            repo.MemberPortal.RiskAssessment_Casualty.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'MemberPortal'.", repo.MemberPortal.SelfInfo, new RecordItemIndex(1));
            repo.MemberPortal.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
            try {
                Report.Log(ReportLevel.Info, "Validation", "(Optional Action)\r\nValidating Exists on item 'MemberPortal.Results_Grid_Row1'.", repo.MemberPortal.Results_Grid_Row1Info, new RecordItemIndex(2));
                Validate.Exists(repo.MemberPortal.Results_Grid_Row1Info, null, false);
                Delay.Milliseconds(0);
            } catch(Exception ex) { Report.Log(ReportLevel.Warn, "Module", "(Optional Action) " + ex.Message, new RecordItemIndex(2)); }
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
