///////////////////////////////////////////////////////////////////////////////
//
// This file was automatically generated by RANOREX.
// DO NOT MODIFY THIS FILE! It is regenerated by the designer.
// All your modifications will be lost!
// http://www.ranorex.com
//
///////////////////////////////////////////////////////////////////////////////

using System;
using System.Collections.Generic;
using System.Text;
using System.Text.RegularExpressions;
using System.Drawing;
using System.Threading;
using WinForms = System.Windows.Forms;

using Ranorex;
using Ranorex.Core;
using Ranorex.Core.Testing;
using Ranorex.Core.Repository;

namespace BackOffice
{
#pragma warning disable 0436 //(CS0436) The type 'type' in 'assembly' conflicts with the imported type 'type2' in 'assembly'. Using the type defined in 'assembly'.
    /// <summary>
    ///The MemberPortal_SignIn_var recording.
    /// </summary>
    [TestModule("0695d056-0865-407a-88a5-3bf415319792", ModuleType.Recording, 1)]
    public partial class MemberPortal_SignIn_var : ITestModule
    {
        /// <summary>
        /// Holds an instance of the _MemberPortalRepository repository.
        /// </summary>
        public static _MemberPortalRepository repo = _MemberPortalRepository.Instance;

        static MemberPortal_SignIn_var instance = new MemberPortal_SignIn_var();

        /// <summary>
        /// Constructs a new instance.
        /// </summary>
        public MemberPortal_SignIn_var()
        {
            MemberPortalLogin = "steve.demo@aegisrslorg.com";
            MemberPortalPassword = "Test!0000";
        }

        /// <summary>
        /// Gets a static instance of this recording.
        /// </summary>
        public static MemberPortal_SignIn_var Instance
        {
            get { return instance; }
        }

#region Variables

        string _MemberPortalLogin;

        /// <summary>
        /// Gets or sets the value of variable MemberPortalLogin.
        /// </summary>
        [TestVariable("43fbb9fb-335d-4ea2-ab98-29453e85b8d6")]
        public string MemberPortalLogin
        {
            get { return _MemberPortalLogin; }
            set { _MemberPortalLogin = value; }
        }

        string _MemberPortalPassword;

        /// <summary>
        /// Gets or sets the value of variable MemberPortalPassword.
        /// </summary>
        [TestVariable("b44b1a11-3945-4f4b-a3f2-c3c857f945eb")]
        public string MemberPortalPassword
        {
            get { return _MemberPortalPassword; }
            set { _MemberPortalPassword = value; }
        }

#endregion

        /// <summary>
        /// Starts the replay of the static recording <see cref="Instance"/>.
        /// </summary>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        public static void Start()
        {
            TestModuleRunner.Run(Instance);
        }

        /// <summary>
        /// Performs the playback of actions in this recording.
        /// </summary>
        /// <remarks>You should not call this method directly, instead pass the module
        /// instance to the <see cref="TestModuleRunner.Run(ITestModule)"/> method
        /// that will in turn invoke this method.</remarks>
        [System.CodeDom.Compiler.GeneratedCode("Ranorex", global::Ranorex.Core.Constants.CodeGenVersion)]
        void ITestModule.Run()
        {
            Mouse.DefaultMoveTime = 300;
            Keyboard.DefaultKeyPressTime = 300;
            Delay.SpeedFactor = 1.00;

            Init();

            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemberPortal.LogIn_Username' at Center.", repo.MemberPortal.LogIn_UsernameInfo, new RecordItemIndex(0));
            repo.MemberPortal.LogIn_Username.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$MemberPortalLogin' with focus on 'MemberPortal.LogIn_Username'.", repo.MemberPortal.LogIn_UsernameInfo, new RecordItemIndex(1));
            repo.MemberPortal.LogIn_Username.PressKeys(MemberPortalLogin, 20);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemberPortal.LogIn_Password' at Center.", repo.MemberPortal.LogIn_PasswordInfo, new RecordItemIndex(2));
            repo.MemberPortal.LogIn_Password.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Keyboard", "Key sequence from variable '$MemberPortalPassword' with focus on 'MemberPortal.LogIn_Password'.", repo.MemberPortal.LogIn_PasswordInfo, new RecordItemIndex(3));
            repo.MemberPortal.LogIn_Password.PressKeys(MemberPortalPassword, 20);
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Mouse", "Mouse Left Click item 'MemberPortal.BtnLogin' at Center.", repo.MemberPortal.BtnLoginInfo, new RecordItemIndex(4));
            repo.MemberPortal.BtnLogin.Click();
            Delay.Milliseconds(0);
            
            Report.Log(ReportLevel.Info, "Invoke action", "Invoking WaitForDocumentLoaded() on item 'MemberPortal'.", repo.MemberPortal.SelfInfo, new RecordItemIndex(5));
            repo.MemberPortal.Self.WaitForDocumentLoaded();
            Delay.Milliseconds(0);
            
        }

#region Image Feature Data
#endregion
    }
#pragma warning restore 0436
}
